### ISSUE TITLE
Cannot use command "php artisan migrate"

### ISSUE THREAD

**Issue by sopanatx** [laravel/pulse#101]
### Pulse Version

1.0.0

### Laravel Version

10.34.2

### PHP Version

8.3

### Description

I can't use the command 'php artisan migrate' because I encounter this error when running the command.
Database: PostgreSQL 16

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
LINE 1: ...(16) not null generated always as (unhex(md5(`key`))), "valu...
                                                             ^ (Connection: pgsql, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, "key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))

<img width="1261" alt="Screenshot 2566-12-02 at 10 55 08" src="https://github.com/laravel/pulse/assets/11361036/62189dfc-a4e0-4e62-8459-0f87db4713f2">

### Steps To Reproduce

-

**Comment by benholmen** [comment]
[From the docs](https://laravel.com/docs/10.x/pulse#installation):

> Pulse's first-party storage implementation currently requires a MySQL database. If you are using a different database engine, such as PostgreSQL, you will need a separate MySQL database for your Pulse data.

**Comment by juhasev** [comment]
PostgreSQL is not supported, only MySQL is for the current beta. I am pretty sure Taylor will add PostgreSQL support in the future, in fact, there is already a pull request for it (with tests failing).

**Comment by sopanatx** [comment]
resolved. Thanks
