### ISSUE TITLE
Does not allow for User Models with non-standard fields

### ISSUE THREAD

**Issue by coleander** [laravel/pulse#102]
### Pulse Version

v1.0.0-beta2

### Laravel Version

10.28.0

### PHP Version

8.2.9

### Description

Hello first of all, cool project!

Installed it on a project I'm working on but I'm getting an error when accessing the dashboard. 
The error seem to stem from Usage.php using the pulse facade calling line 333 or 335 (depending on user model path). 
```
} elseif (class_exists(\App\Models\User::class)) {
    return \App\Models\User::whereKey($ids)->get(['id', 'name', 'email']);
} elseif (class_exists(\App\User::class)) {
    return \App\User::whereKey($ids)->get(['id', 'name', 'email']);
}
```

It's trying to get a few attributes of the users it's fetching, now the issue is that those attributes doesn't always exists, for example in my project we don't use email at all, but instead a different db field name, so the attribute name is different and email doesn't exist. 

Maybe an easy way to fix it would be to allow an array of fields in the config, so users could just define some fields? Or maybe some magic that tries to figure out what correct fields, anyways it's bugging out as of now. 

### Steps To Reproduce

Install pulse on a Laravel project where the user model doesn't for example have the email field or any of the other wanted fields in the code. Then access the dashboard and the bug will appear.

**Comment by woodspire** [comment]
The solution is to use Pulse::users()

Had the same problem; User model didn't have a "name" field (split into first + last name)

https://laravel.com/docs/10.x/pulse#application-usage-card

**Comment by jessarcher** [comment]
Thanks @woodspire - that's the correct solution :+1:
