### ISSUE TITLE
Error on migration on sqlite

### ISSUE THREAD

**Issue by nezaboravi** [laravel/pulse#107]
### Pulse Version

1.0.0

### Laravel Version

10.4.2

### PHP Version

8.2

### Description

On first migration error:

 SQLSTATE[HY000]: General error: 1 no such function: md5 (Connection: sqlite, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar not null, "key" text not null, "key_hash" varchar as (unhex(md5(`key`))), "value" text not null))

### Steps To Reproduce

I have tried to install it on existing app, and when step to migrate db came, i got that error.

**Comment by jessarcher** [comment]
Hi @nezaboravi,

Pulse currently only works with a MySQL database, as mentioned at https://laravel.com/docs/10.x/pulse#installation.

I can see how this would be annoying in a project that uses SQLite for local development. I think we'll look at making it possible to disable the Pulse migrations in a local environment.

I've done some work in #64 to add Postgres support. It might be trivial to add SQLite support as well, although I don't think I'd recommend using Pulse with SQLite in production.

**Comment by ryanpitts1** [comment]
@jessarcher we use SQLite for our tests in github actions. Now our actions pipeline fails every time when trying to run migrations. Is there a way we can disable the pulse migration if the environment is `testing`?

**Comment by eleftrik** [comment]
Thanks for the hint, @joelhinz 👍

**Comment by timacdonald** [comment]
```xml
// phpunit.xml
<server name="PULSE_ENABLED" value="false"/>
```

This is the way 👍

**Comment by ryanpitts1** [comment]
Thanks for the hint @joelhinz and @timacdonald!

**Comment by nezaboravi** [comment]
> ```
> // phpunit.xml
> <server name="PULSE_ENABLED" value="false"/>
> ```
> 
> This is the way 👍

This is the way.
