### ISSUE TITLE
Migration fails when `sql_require_primary_key` is set

### ISSUE THREAD

**Issue by haugstrup** [laravel/pulse#108]
### Pulse Version

1.0beta

### Laravel Version

10

### PHP Version

8.1

### Description

When `sql_require_primary_key` is set, the Pulse migration fails:

```
SQLSTATE[HY000]: General error: 3750 Unable to create or change a table without a primary key, when the system vari  
  able 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message.  
   Note that tables without a primary key can cause performance problems in row-based replication, so please consult   
  your DBA before changing this setting. (Connection: mysql, SQL: create table `pulse_values` (`timestamp` int unsign  
  ed not null, `type` varchar(255) not null, `key` text not null, `key_hash` char(16) character set binary as (unhex(  
  md5(`key`))), `value` text not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')  
```

It errors on the first table, but presumably will fail on all three tables. This setting is required on Digital Ocean Managed MySQL servers so Pulse can't be installed for any application backed by that service.

`pulse_values` and `pulse_aggregates` tables both have a `unique` index so both tables can probably be created by disabling `sql_require_primary_key` while the tables are being created.

But `pulse_entries` doesn't appear to have a column or index that can be used as a primary key so I don't know what to do there.

### Steps To Reproduce

* Set `sql_require_primary_key` to true in your MySQL configuration.
* Attempt to install Pulse

**Comment by ahinkle** [comment]
FWIW, You can reach out to DO to get the `sql_require_primary_key` flag removed.

**Comment by haugstrup** [comment]
Not really a great trade-off since it can break replication 🤷

**Comment by jbrooksuk** [comment]
While I agree it's not ideal, you can also make an API request to DO to change this setting; https://stackoverflow.com/questions/62418099/unable-to-create-or-change-a-table-without-a-primary-key-laravel-digitalocean

**Comment by driesvints** [comment]
@jessarcher @timacdonald could we get auto incrementing primary keys on the tables or was there a big reason we didn't?

**Comment by GalahadXVI** [comment]
Is there any reason why we can't publish the migration files?

As placing this at the beginning of up() solves the issue:
`\Illuminate\Support\Facades\DB::statement('SET SESSION sql_require_primary_key=0');`

**Comment by jbrooksuk** [comment]
Migrations should be publishable soon, https://github.com/laravel/pulse/pull/81

**Comment by zoispag** [comment]
Similar issue with Telescope: https://github.com/laravel/telescope/pull/1407
The suggestion was to publish the migration and modify as seen fit. I still think that the provided migrations should always have primary keys, to allow replication.

**Comment by timacdonald** [comment]
This will be fixed in https://github.com/laravel/pulse/pull/142/

If you have already run the migrations you will need to add this column manually.

**Comment by haugstrup** [comment]
Big thank you for this change -- those mimic the columns I added manually, but it's fantastic that Pulse will work out-of-the-box going forward. It's a fantastic package!
