### ISSUE TITLE
Change requested columns for user name in users table

### ISSUE THREAD

**Issue by shanke-pvex** [laravel/pulse#109]
I removed the name column from users table and added firstname and lastname.
So now i get this error: Column not found: 1054 Unknown column 'name' in 'field list'
Is there a possibility to to adjust this?

**Comment by pierrepavlov** [comment]
There's information on this here: https://laravel.com/docs/10.x/pulse#dashboard-cards

**Comment by jbrooksuk** [comment]
Please see https://laravel.com/docs/10.x/pulse#application-usage-card

**Comment by shanke-pvex** [comment]
Perfect. Thanks a lot.
