### ISSUE TITLE
Killing pulse:work Orphan Process without htop

### ISSUE THREAD

**Issue by relaypilot** [laravel/pulse#116]
### Pulse Version

1.0.0

### Laravel Version

10.34.2

### PHP Version

8.3

### Description

After running `php artisan pulse:work` command, the process runs correctly in the background.

However, after running `php artisan pulse:purge` and uninstalling the package with `composer remove laravel/pulse`, the process still exists, and entries keep on getting added to the `pulse_aggregates` table.

Is there a way to stop the process without using `htop`? Something like `horizon:purge` that kills orphan procs.

It would be useful to have a command to kill the orphan `pulse:work` processes.

### Steps To Reproduce

- Install Pulse
- Run `php artisan pulse:work` to start a process
- Run pulse:purge and uninstall Pulse => the process is still running

**Comment by ahinkle** [comment]
Horizon works in the same way. Laravel core doesn't know anything about the pulse commands once it's uninstalled. Not really an issue.

I think it should be up to the user knowing what you're getting into when uninstalling the package.
