### ISSUE TITLE
Using custom db connection - with missing table

### ISSUE THREAD

**Issue by toitzi** [laravel/pulse#122]
### Pulse Version

1.0.0

### Laravel Version

10.34.2

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0.33 for macOS 14.3 on arm64 (DBngin)

### Description

When you use a custom database connection for pulse, and run the migrations without the database already existing, an exception will be thrown. While this is not wrong, usually when you run database migrations and the database does not exist, laravel will print it to the console and ask you if you want to create the non-existent database ([here](https://github.com/laravel/framework/blob/37cb3450150cf75af787dc9bcd8de08370024008/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L192)). The problem here seems to be the following:

When running migrations, laravel will run the `prepareDatabase()` function at the beginning see [here](https://github.com/laravel/framework/blob/37cb3450150cf75af787dc9bcd8de08370024008/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L84). At the point of laravel doing this, the migrations are not yet loaded / included, so it will always check against your defualt database connection. After that it will evaluate the migration path, include them and [migrate](https://github.com/laravel/framework/blob/37cb3450150cf75af787dc9bcd8de08370024008/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L89). Inside the `runMigration` function the database connection get's evaluated via the `getConnection` method of the migration itself ([here](https://github.com/laravel/framework/blob/37cb3450150cf75af787dc9bcd8de08370024008/src/Illuminate/Database/Migrations/Migrator.php#L402)). This is where the default migration of pulse will return the pulse connection. Since the database does not exists, an exception is thrown at this point.

I am not quite sure on how to fix it, the solutions that come up my mind right now are:

- Instead of using the `getConnection` method to return the schema in the pulse migrations, somewhat overwrite the default laravel connection to the pulse connection and then after the migrations writing it back to the default `DB_CONNECTION` env variable. (Have not tried if this would actually work but i think so)

- Another solution might be creating an issue/pr agains the laravel framework and running the prepare database function after the migration has been loaded, and against it's connection. I can imagine that this would be not a small task, and that some performace considerations might take place here on running it for every migration

- Last and not least: Leave it as is, throw the exception and let the developer create the database by himself

### Steps To Reproduce

1. Install pulse
2. Set the `PULSE_DB_CONNECTION` env variable to an existing connection but without the configured `database` in the connection existing.
3. Run `php artisan migrate`

**Comment by timacdonald** [comment]
This is an enhancement that would need to be made to Laravel itself, not Pulse.

Would love to see this fixed in the framework. Going to close this here as the bug is not Pulse related.
