### ISSUE TITLE
Migration fails in pgsql 

### ISSUE THREAD

**Issue by UshurbakiyevDavlat** [laravel/pulse#129]
### Pulse Version

1.0.0

### Laravel Version

10.34.2

### PHP Version

8.2

### Database Driver & Version

postgres:13

### Description

  2023_06_07_000001_create_pulse_tables .................................................................................................. 20ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: ...) not null generated always as (unhex(md5(`key`))), "value" ...
                                                             ^ (Connection: pgsql, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, "key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))

### Steps To Reproduce

I used postgres:13 image in docker-compose, and tried to run migration of pulse.

**Comment by jessarcher** [comment]
Please see https://laravel.com/docs/10.x/pulse#installation and #64
