### ISSUE TITLE
Avatar URL gets overridden regardless of custom user resolution

### ISSUE THREAD

**Issue by JanniGrabe** [laravel/pulse#133]
### Pulse Version

1.0.0-beta2

### Laravel Version

10.34.2

### PHP Version

8.2.12

### Database Driver & Version

MySQL 8.0.32

### Description

Even if I define an 'avatar' array key as described in the docs
```
Pulse::users(function ($ids) {
    return User::findMany($ids)->map(fn ($user) => [
        'id' => $user->id,
        'name' => $user->name,
        'extra' => $user->email,
        'avatar' => $user->avatar_url,
    ]);
});
```

it will get overriden by the Collection mapping in src/Livewire/Usage.php.

https://github.com/laravel/pulse/blob/fca8a98808dc10c3e75d72614233ed913f6b2048/src/Livewire/Usage.php#L68-L70

Also, the gravatar URL includes an 'email' array key that is not stated in the docs, I would suggest to either replace that with 'extra' or add email to the example.

### Steps To Reproduce

1. Install Laravel Pulse
2. Insert
    ```
    Pulse::users(function ($ids) {
    return User::findMany($ids)->map(fn ($user) => [
        'id' => $user->id,
        'name' => $user->name,
        'extra' => $user->email,
        'avatar' => $user->avatar_url,
    ]);
    });
    ```
    into your AuthServiceProvider.php's boot() function
3. Open Laravel Pulse

**Comment by jbrooksuk** [comment]
This should be fixed in the next release.
