### ISSUE TITLE
Crash in `FETCH_ASSOC` mode

### ISSUE THREAD

**Issue by daniser** [laravel/pulse#135]
### Pulse Version

1.0.0-beta2

### Laravel Version

10.34.2

### PHP Version

8.1.26

### Database Driver & Version

MySQL 8.0.30

### Description

Pulse fails to work in `FETCH_ASSOC` mode (example: `Livewire\Cache.php:44`).

### Steps To Reproduce

Enable `FETCH_ASSOC` mode:
```php
<?php

namespace App\Listeners;

use Illuminate\Database\Events\StatementPrepared;

class StatementPreparedListener
{
    /**
     * Handle the event.
     */
    public function handle(StatementPrepared $event): void
    {
        $event->statement->setFetchMode(\PDO::FETCH_ASSOC);
    }
}
```

**Comment by jessarcher** [comment]
That's a tricky one. I can't think of a good way to change it back to `FETCH_OBJ` just for Pulse queries, as that event is the last thing fired before the statement is executed. We could try to bind a later listener to change it back, or add some code to handle different return types, but I'd ideally like to see more people with this issue before adding more code to the package.

Would it be possible for you to set the fetch mode conditionally? Either by inspecting the statement or `request()`, or by binding another listener that sets it back on a Pulse requests only (probably by configuring an additional middleware for Pulse)?

**Comment by daniser** [comment]
@jessarcher I'd prefer to move my project to `FETCH_OBJ` globally, it's long overdue. But thanks anyway!

**Comment by timacdonald** [comment]
I would recommend creating a middleware that registers this listener (rather than in a service provider), then you can apply the middleware to your app routes but not Pulse.

You can also then use the middleware as a migration path for your whole application 👍
