### ISSUE TITLE
pulse not populating db entries

### ISSUE THREAD

**Issue by rebbieboi** [laravel/pulse#143]
### Pulse Version

v1.0.0-beta3

### Laravel Version

10.34.2

### PHP Version

8.1.26

### Database Driver & Version

mysql  Ver 14.14 Distrib 5.7.35-38, for debian-linux-gnu (x86_64) using  7.0

### Description

no db entries are recorded for the tables pulse_entries, pulse_aggregates, and pulse_values

note that the system is in a cluster so the DB is hosted on a different server.

![pulse](https://github.com/laravel/pulse/assets/714513/0e5c63c4-a24a-4bfb-9c9a-be7aeddd1ec6)

### Steps To Reproduce

*

**Comment by jessarcher** [comment]
Have you customized the ingest driver to use Redis? I.e. `PULSE_INGEST_DRIVER=redis`

**Comment by rebbieboi** [comment]
> Have you customized the ingest driver to use Redis? I.e. `PULSE_INGEST_DRIVER=redis`. If so, you will need to run the `pulse:work` Artisan command.
> 
> Otherwise, can you enable logging for Pulse and see if there are any exceptions: https://laravel.com/docs/10.x/pulse#pulse-exceptions

Where can I find the file for https://laravel.com/docs/10.x/pulse#pulse-exceptions? thank you

**Comment by jessarcher** [comment]
> Where can I find the file for https://laravel.com/docs/10.x/pulse#pulse-exceptions? thank you

You can place this in the `boot` method of the `app/Providers/AppServiceProvider.php` file.

**Comment by rebbieboi** [comment]
> > Where can I find the file for https://laravel.com/docs/10.x/pulse#pulse-exceptions? thank you
> 
> You can place this in the `boot` method of your `app/Providers/AppServiceProvider.php` file.

Managed to see the errors now:

An exception happened in Pulse {"message":"SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (tt.pulse_entries) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER (Connection: mysql, SQL: insert into `pulse_entries` (`key`, `timestamp`, `type`, `value`)

**Comment by jessarcher** [comment]
This sounds like the same issue as #108 and #136 which should be fixed when #142 is released :+1:

**Comment by driesvints** [comment]
Thanks. This will be fixed by https://github.com/laravel/pulse/pull/142

**Comment by rebbieboi** [comment]
thank you!
