### ISSUE TITLE
Add Prometheus endpoints to retrieve data

### ISSUE THREAD

**Issue by nicolus** [laravel/pulse#144]
Hi,

This looks like a really useful project, but I'm already doing all of my monitoring with Grafana, and I'd really like to keep it that way instead of having multiple dashboards spread across different tools, and I'm sure I'm not the only one.

Do you think it would be a good idea to add some configurable Prometheus/VictoriaMetrics endpoints that could be used to pull all that useful data into Grafana ?

**Comment by timacdonald** [comment]
This is not something we are looking at adding.

the data is available in the applications data base and could be manually access to expose to a public API.

**Comment by nicolus** [comment]
> the data is available in the applications data base and could be manually access to expose to a public API.

All right thanks, I'll try to play with this over the week-end.
