### ISSUE TITLE
Pulse 1.0.0-beta3 version is not working due to appending APP_URL.

### ISSUE THREAD

**Issue by ahaneef29** [laravel/pulse#145]
### Pulse Version

1.0.0-beta3

### Laravel Version

10.34.2 

### PHP Version

8.2.13 

### Database Driver & Version

Mysql

### Description

I installed Pulse 1.0.0-beta3 version today which not loading Pulse dashboard due to the appending APP_URL., if i commented the APP_URL from .env file. Its working fine. i tried production server too and its same.

Please check the screenshot.
<img width="1753" alt="pulse screenshot" src="https://github.com/laravel/pulse/assets/10325179/a6c45531-8a9f-465b-8a8c-50aacab95ac9">

### Steps To Reproduce

Install the Pulse 1.0.0-beta3 version into existing Laravel app.

**Comment by jbrooksuk** [comment]
I'm not able to replicate this myself. Also, the Request URL doesn't look like it's related to Pulse, as it's simply your `APP_URL` and a cache query of some kind.

Can you try disabling Debugbar too?

**Comment by sinnbeck** [comment]
Do you perhaps have a /config/livewire.php file? Check if it has a `asset_url` set. If it does, try removing it.. It will overwrite livewire's own `/livewire/livewire.js` url

**Comment by ahaneef29** [comment]
@sinnbeck Yes, I have updated `asset_url` to `null` in /config/livewire.php file

`'asset_url' => null, `

Which is working fine.

Thank you @sinnbeck @jbrooksuk

**Comment by sinnbeck** [comment]
@ahaneef29 Just remove it completely. Its not part of the livewire config file by default

Check the default here
https://github.com/livewire/livewire/blob/main/config/livewire.php

**Comment by ahaneef29** [comment]
@sinnbeck removed Thank you again.

**Comment by jessarcher** [comment]
Is this resolved now? If so, please close the issue. Thanks!

**Comment by driesvints** [comment]
Guess this is resolved, thanks.

**Comment by timacdonald** [comment]
Opened a PR to address this moving forward: https://github.com/laravel/pulse/pull/266
