### ISSUE TITLE
Target class [web] does not exist.

### ISSUE THREAD

**Issue by eusonlito** [laravel/pulse#146]
### Pulse Version

^1.0@beta

### Laravel Version

10.34.2

### PHP Version

8.2.13

### Database Driver & Version

MySQL 8.0.35

### Description

After install, I get an error due the non existing middleware `web`.

![Screenshot from 2023-12-05 12-25-55](https://github.com/laravel/pulse/assets/644551/6e7e9fd6-6283-4287-a7c8-1acb807886ed)

I have removed all middlewares from `config/pulse.php`:

```php
    /*
    |--------------------------------------------------------------------------
    | Pulse Route Middleware
    |--------------------------------------------------------------------------
    |
    | These middleware will be assigned to every Pulse route, giving you the
    | chance to add your own middleware to this list or change any of the
    | existing middleware. Of course, reasonable defaults are provided.
    |
    */

    'middleware' => [
    ],
```

But `web` middleware is set as fixed on code:

https://github.com/laravel/pulse/blob/e6e02586f1a2a21d98612c22ab24310c81f3b88d/src/PulseServiceProvider.php#L96-L109

### Steps To Reproduce

1. Create a Laravel project and remove `web` middleware.
2. Install Pulse.

**Comment by crynobone** [comment]
`web` middleware group is available by default in default Laravel application and Pulse needs it to handle to authorize user access to Pulse. If you intend to remove `web` you need to provide a proper replacement to handle this requirement.

**Comment by eusonlito** [comment]
And can not be checked before?

I know that can work with:

```php
    protected $middlewareGroups = [
        'web' => [],
```

But, why is a requirement if doesn't do nothing?

Thanks!

**Comment by timacdonald** [comment]
Fix up: https://github.com/laravel/pulse/pull/152
