### ISSUE TITLE
ArgumentCountError

### ISSUE THREAD

**Issue by remievraere** [laravel/pulse#148]
### Pulse Version

v1.0.0-beta3

### Laravel Version

10.34.2

### PHP Version

8.2.10

### Database Driver & Version

Mysql 8.0.27

### Description

Hi!

I have this error 

ArgumentCountError
Too few arguments to function with(), 0 passed in PATH/views/b8781141701c873b2952e3dfa136fe32.php on line 38 and at least 1 expected
Coming from the request to : https://MYAPP/livewire/update

This error disappears when i'm removing 
`@scroll.debounce.5ms="scroll"`
From vendor/laravel/pulse/resources/views/components/scroll.blade.php

Do you have any idea of why? And how this is important? I mean, it seems to impact the scroll but can't really tell more.

I'm not really familiar with Livewire, so that's the best of help I could provide.

Thank's in advance!

### Steps To Reproduce

Not sure how you could replicate as this is a project I cant share, and I didn't try on fresh install.

**Comment by driesvints** [comment]
Please add the exact beta version.

**Comment by remievraere** [comment]
During the meantine, I tried to update to laravel 10.35 and laravel pulse v1.0.0-beta4. But I have the same error.

About Livewire :
```
$ composer show livewire/livewire
name     : livewire/livewire
descrip. : A front-end framework for Laravel.
versions : * v3.2.6
```

Here is the stacktrace : https://flareapp.io/share/x5MZvaNm

**Comment by remievraere** [comment]
I've finally managed to find a solution. I first tried to change the `@scroll` to `v-on:scroll`
And it was working, so I suspected that I might have a blade directive called scroll and that's the case. 
If I remove the directive, and optimize:clear, it's working.
May be using the shorthand syntax is not a good solution in this case?
Would you like me to make a merge request about that?

**Comment by timacdonald** [comment]
@remievraere thanks for digging into this for us.

I've just created a PR that should address this issue: https://github.com/laravel/pulse/pull/170

Thanks!

**Comment by timacdonald** [comment]
Actually, @remievraere I would instead recommend not registering the blade directive on the Pulse route.

You might need to move the directive registration into a middleware that is applied to your whole app, but not Pulse.

**Comment by remievraere** [comment]
No problem, i will do this. Thank's for your work.
