### ISSUE TITLE
Throwing SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list'

### ISSUE THREAD

**Issue by rajenindianic** [laravel/pulse#162]
### Pulse Version

v1.0.0-beta5

### Laravel Version

10.35.0

### PHP Version

8.2.12

### Database Driver & Version

 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Description

I am converting a core php application to Laravel, so, I need to use the current database wchich I cant change.

In my users table primery key is UserID,
In my User model `public $primaryKey = "UserID"`

I am getting above given error

### Steps To Reproduce

just rename primery key of users table to UserID,
add `public $primaryKey = "UserID";` to User model

**Comment by jbrooksuk** [comment]
You should add an auto-incrementing primary key to your users table, anyway.

But, you could also configure how Pulse fetches and returns User data; https://laravel.com/docs/10.x/pulse#application-usage-card
