### ISSUE TITLE
net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by sandesh556** [laravel/pulse#164]
### Pulse Version

1.0.0-beta-5

### Laravel Version

10.35.0

### PHP Version

8.2.0

### Description

![Screen Shot 2023-12-06 at 3 14 41 PM](https://github.com/laravel/pulse/assets/79452740/b08d953e-aafc-4be4-951e-ad10cd5d7fb4)
![Screen Shot 2023-12-06 at 3 18 08 PM](https://github.com/laravel/pulse/assets/79452740/badd6775-526a-40e9-9e91-1aee19542ec8)
![Screen Shot 2023-12-06 at 3 29 40 PM](https://github.com/laravel/pulse/assets/79452740/4dc9b8d5-62f3-4780-8bab-4989d5aa7e41)

Also saw some existing issues created for this, none of those helped, also noticed none of them had a path in the url

### Steps To Reproduce

So installed the new version of Pulse and did all the necessary steps to publish it. And then when I get to the dashboard this is what I see. But the APP_URL has a path associated with it and the URL called in the console doesn't take that path Pulse

**Comment by maloun96** [comment]
I have that issue too.

**Comment by sinnbeck** [comment]
Check that the route actually exists with `php artisan route:list`. It is a route that livewire adds.

It should look like this
```
GET|HEAD        livewire/livewire.js ........................................................................................................................................................... Livewire\Mechanisms › FrontendAssets@returnJavaScriptAsFil

**Comment by sinnbeck** [comment]
Just noticed that you have `/public` in your url. Seems you didnt set up your webserver to point to the public directory

![image](https://github.com/laravel/pulse/assets/13980140/5fe1c797-49f3-48fb-81e8-ef9b10f52ce4)

Fix this first.

**Comment by maloun96** [comment]
https://admin.blablabla/livewire/livewire.js?id=f477dd12. I can open in a new tab, I see the code, but fetching with XHR results 404.
I alos have the route

**Comment by sandesh556** [comment]
> @sandesh556 Just noticed that you have `/public` in your url. Seems you didnt set up your webserver to point to the public directory
> 
> ![image](https://private-user-images.githubusercontent.com/13980140/288367440-5fe1c797-49f3-48fb-81e8-ef9b10f52ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTgyNzQsIm5iZiI6MTcwMTg1Nzk3NCwicGF0aCI6Ii8xMzk4MDE0MC8yODgzNjc0NDAtNWZlMWM3OTctNDlmMy00OGZiLTgxZTgtZWY5YjEwZjUyY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEwMTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjdjNDQyYzEzYjNhNjdiZGI1MmZmYTNlMmU4ZmQ1NzYyYzJlYThiZDVjMTZmYTMzM2Q2YWMwYWVlMzNjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_BBmL0-lJuxkupDQuvL05p7ahZRe2vJJ_ud0Nbs5zE)
> 
> Fix this first.. Or use `php artisan serve` to serve the website while developing

This doesn't explain why the APP_URL is not being taken. Tried a new laravel app using Serve that works, pulse renders the dashboard. But if there is a path involved in the APP_URL why is it not being considered

**Comment by jbrooksuk** [comment]
What version of Livewire are you using? Also, I believe @sinnbeck is on to something, Laravel isn't meant to be configured under a sub-directory like that.

**Comment by maloun96** [comment]
Fixed
 ```
 location = /livewire/livewire.js {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}
```

in Ngnix

**Comment by timacdonald** [comment]
Opened a PR to address this moving forward: https://github.com/laravel/pulse/pull/266
