### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'key' 

### ISSUE THREAD

**Issue by mferrara** [laravel/pulse#167]
### Pulse Version

1.0.0-beta5

### Laravel Version

10.35.0

### PHP Version

8.2

### Livewire Version

3.2.6

### Database Driver & Version

MySQL 8 (Managed Digital Ocean)

### Description

I'm running in an issue with ingesting and the following errors are thrown..

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'key' at row 159 (Connection: pulse, SQL: insert into `pulse_entries` (`key`, `timestamp`, `type`, `value`) values`

I've removed the rest of the query as there's lots of stuff there I don't want public but it looks like some _very_ long mysql queries are being used as the key and causing the issue. In my application I've replaced those queries and the issue persists, so it seems as though the ingest jobs will continue to retry.

### Steps To Reproduce

Run a MySQL query with a `whereHasIn()` with a few hundred/thousand keys (long enough to be longer than the max length of a TEXT column) in it - the query entry to the `pulse_entries` table should end up failing.

**Comment by timacdonald** [comment]
@mferrara I would recommend publishing the migrations and changing the `TEXT` columns to `MEDIUMTEXT`.

We might also consider changing this as the default column type if we see some more reports of this issue.

Sorry for the troubles you've had there.

**Comment by rikvdlooi** [comment]
Just reporting that we experienced this issue as well.
Thanks for the recommendation Tim.

**Comment by timacdonald** [comment]
No worries. I think we will make these `mediumtext` by default today.
