### ISSUE TITLE
Memory leak when running tests in Bitbucket Pipeline after installing Laravel Pulse

### ISSUE THREAD

**Issue by BernhardK91** [laravel/pulse#181]
### Pulse Version

1.0.0-beta5

### Laravel Version

10.34.2

### PHP Version

8.2.13

### Livewire Version

3.2.6

### Description

After installing Laravel Pulse into a real-world application with currently round about 400 tests, I am getting memory leak in the Bitbucket Pipeline when running the tests.

First I thought, it could be caused by running the processes parallel, but even without parallel running, the memory leak occurs. 
I am unable to reproduce the issue locally yet.

I am not sure if this is related to the installation of Laravel Pulse or if it is a coincidence. I am aware that this is not much information to tweak the issue, but I thought creating an issue might help, if others have the problem as well, and we can collect cases and find potential causes. 

### Steps To Reproduce

Currently, I am unable to reproduce the issue in another environment.

**Comment by driesvints** [comment]
You can disable Pulse in a test suite with PULSE_ENABLED.

**Comment by BernhardK91** [comment]
Oh wow... That was too easy... 🤯 I could have thought of it myself 🙊

Anyway, thanks a lot! 🥇

**Comment by timacdonald** [comment]
`v1.0.0-beta8` has been tagged which should resolve the memory leak in the testsuite.
