### ISSUE TITLE
The Queue card shows SQS queue twice (one with the queued and one with processed and processing items)

### ISSUE THREAD

**Issue by BernhardK91** [laravel/pulse#183]
### Pulse Version

1.0.0-beta5

### Laravel Version

10.34.2

### PHP Version

8.2.13

### Livewire Version

3.2.6

### Description

We are running in an AWS environment and using SQS as queue driver. Currently, we have 1 queue, but Pulse shows it twice. The upper one has the "queued" jobs and the second one has the "processing" and "processed" jobs.

![image](https://github.com/laravel/pulse/assets/5526334/638f894c-02a2-4df5-86d5-6f3ca026c871)

The database (`pulse_aggregates`) shows that the SQS entries are logged with different names. Some with the driver name and some with the full SQS address:

![image](https://github.com/laravel/pulse/assets/5526334/3c6d00db-02a9-46cd-8da0-296711c6fdde)

### Steps To Reproduce

Currently, I do not have a second project that uses SQS queue, so I cannot share reproduction steps.

**Comment by timacdonald** [comment]
We are aware of this and will get it sorted in the next beta. Thanks for reporting.

**Comment by timacdonald** [comment]
This will be fixed in https://github.com/laravel/pulse/pull/187

We can follow that PR.
