### ISSUE TITLE
Can't install on php 8.1

### ISSUE THREAD

**Issue by m-ostadi** [laravel/pulse#190]
### Pulse Version

1.0 beta5

### Laravel Version

9.52.7

### PHP Version

8.1.25

### Livewire Version

*

### Description

laravel/pulse dev-card-customisation requires php ^8.2 -> your php version (8.1.25) does not satisfy that requirement.

### Steps To Reproduce

composer require laravel/pulse

**Comment by driesvints** [comment]
What's "dev-card-customisation"?

**Comment by jbrooksuk** [comment]
@m-ostadi this is an old branch. You should use one of the tagged releases.
