### ISSUE TITLE
Show Blank Page with error.

### ISSUE THREAD

**Issue by phpnil** [laravel/pulse#192]
### Pulse Version

1.0.0-beta2

### Laravel Version

10.0.0

### PHP Version

8.2.10

### Livewire Version

3.2.6

### Description

We installed Pulse on Project, and it showed an error on Popup.

Call to undefined method Illuminate\Support\Benchmark::value()

![Uploading Screenshot 2023-12-08 at 6.02.47 PM.png…]

### Steps To Reproduce

Install Pulse on Laravel 10

### Configuration
Environment ......................................................................................................................................
Application Name ................................................................................................................ PO
Laravel Version ........................................................................................................................... 10.0.0
PHP Version ............................................................................................................................... 8.2.10
Composer Version ........................................................................................................................... 2.3.7
Environment ................................................................................................................................ local
Debug Mode ............................................................................................................................... ENABLED
URL .................................................................................................................................... localhost
Maintenance Mode ............................................................................................................................. OFF

Cache ............................................................................................................................................
Config .................................................................................................................................... CACHED
Events ................................................................................................................................ NOT CACHED
Routes .................................................................................................................................... CACHED
Views ..................................................................................................................................... CACHED

Drivers ..........................................................................................................................................
Broadcasting ................................................................................................................................. log
Cache ....................................................................................................................................... file
Database ................................................................................................................................... mysql
Logs ....................................................................................................................................... daily
Mail ........................................................................................................................................ smtp
Queue ................................................................................................................................... database
Session ..................................................................................................................................... file

Localization .....................................................................................................................................
Installed ............................................................................................................................. en, es, fr
LaravelLang\Attributes\Plugin .............................................................................................................. 2.5.1
LaravelLang\Lang\Plugin .................................................................................................................. 12.24.2
Protected Locales ............................................................................................................................. en
Publisher Version ......................................................................................................................... 14.7.1

Livewire .........................................................................................................................................
Livewire .................................................................................................................................. v3.2.6

<img width="1511" alt="Screenshot" src="https://github.com/laravel/pulse/assets/6614063/007968b5-19df-4306-8583-ba4231555f10">

**Comment by driesvints** [comment]
Hi there. There has to be more to it than just installing Pulse. Please provide more details to reproduce this and preferable a repo. Also please let us know the exact beta version you're using?

**Comment by sinnbeck** [comment]
Make sure you have the newest version of laravel. Run `composer update`

Most certainly you have an old version.

**Comment by jbrooksuk** [comment]
Please try updating Pulse to 1.0.0-beta5. If this still happens, please feel free to re-open this issue.
