### ISSUE TITLE
Class "Asset" not found

### ISSUE THREAD

**Issue by dragonfire1119** [laravel/pulse#195]
### Pulse Version

1.0.0

### Laravel Version

10.35.0

### PHP Version

8.1.24

### Livewire Version

3.0.2

## Servers Card

When I have the servers card, it gives me:

```
Class "Asset" not found
```

The issue seems to be with:

```
@js
```

If I remove all or `@js`, it will render.

```
vendor/laravel/pulse/resources/views/livewire/servers.blade.php:70
```

https://github.com/laravel/pulse/blob/9c65d50d22529b6034b520257d105ee9b279ca3d/resources/views/livewire/servers.blade.php#L70

## Queues Card

This happens on the queues card too:

```
syntax error, unexpected identifier "queued", expecting ")"
```

If I remove all `@js` calls, it renders.

```
vendor/laravel/pulse/resources/views/livewire/queues.blade.php:81
```

https://github.com/laravel/pulse/blob/9c65d50d22529b6034b520257d105ee9b279ca3d/resources/views/livewire/queues.blade.php#L76

### Steps To Reproduce

I just go to the Pulse dashboard, and it pops up an error. When using servers or queue cards.

## Solution

Changed:

```
@js(<code>)
```

to:

```
{{ <code> }}
```

**Comment by ahinkle** [comment]
Can you create a replicable repository or unit test of this problem? We need more details.

**Comment by jbrooksuk** [comment]
Please provide us with the exact version of Pulse you're running. v1.0.0-beta5 is currently the latest version, so please ensure you're installing that.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by jessarcher** [comment]
I've made some changes to the charts in #206. Still using `@js` though so I don't know if it will help. I can't think of any reason why `@js` could cause that error and I haven't seen the error locally.

**Comment by dragonfire1119** [comment]
@ahinkle I will delve deeper into this when my schedule allows.

@driesvints It is noteworthy that the closure of this matter took place with remarkable speed.

@jbrooksuk My current Laravel Pulse version is v1.0.0-beta5.

@jessarcher I appreciate your assistance. At the moment, I have simply copied your components and imported them as if they were custom components, with the `@js` replaced by `{{ }}`. 

Is the `@js` syntax derived from Livewire? I've had difficulty finding documentation on the new site; it appears that only the previous Livewire site contains relevant information. I am unfamiliar with Livewire, which prompted my inquiry.
