### ISSUE TITLE
name field required in user table

### ISSUE THREAD

**Issue by zimonline** [laravel/pulse#197]
### Pulse Version

1.0@beta

### Laravel Version

10.35.0

### PHP Version

8.2.3

### Livewire Version

N/A

### Database Driver & Version

8.0.32

### Description

Can we make the user (name) a config option. My user table contains firstname,lastname fields.

### Steps To Reproduce

Change the name field in the users table to something else.

**Comment by joryacooper** [comment]
same here when I installed it in my application this morning, my user table doesn't have a name column. 

Make it optional?

**Comment by timacdonald** [comment]
Thanks, @ahinkle for providing the answer here.
