### ISSUE TITLE
SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "user_usage" already exists

### ISSUE THREAD

**Issue by mrkazmierczak** [laravel/pulse#198]
### Pulse Version

dev-card-customisation 74895e4

### Laravel Version

10

### PHP Version

8.1

### Livewire Version

2.12.6

### Database Driver & Version

PostgreSQL 15

### Description

After composer require laravel/pulse and run php artisan migrate I have an error

`  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "user_usage" already exists (Connection: pgsql, SQL: create index "user_usage" on "pulse_jobs" ("date", "user_id"))`

### Steps To Reproduce

I already have a project and I was trying to install Pulse on it with composer require laravel/pulse. After php artisan db:wipe and php artisan migrate:fresh --seed I have this error.

**Comment by jbrooksuk** [comment]
Please use the latest tagged version of Pulse. It appears you're using an older version.
