### ISSUE TITLE
Running test with mysql database throws too many connections or memory issue

### ISSUE THREAD

**Issue by walterdis** [laravel/pulse#200]
### Pulse Version

latest

### Laravel Version

10.32

### PHP Version

8.1.9

### Livewire Version

dont know

### Database Driver & Version

MySQL 8.0.31 for macOS 14.0 on arm64 (Docker)

### Description

Hello,

When I run tests using the MySQL database with --parallel, even with Redis, the tests stop in the middle, giving me the error message: "Too many connections." 
```
[1040] Too many connections (Connection: mysql, SQL: drop database if exists `project_testing_test_2`))
```

If i run without --parallel, it's giving me the memory limit exception
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 565

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 565
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vendor/pestphp/pest/src/Plugins/Actions/CallsShutdown.php on line 1

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vendor/pestphp/pest/src/Plugins/Actions/CallsShutdown.php on line 1
```

Am I doing something wrong?

### Steps To Reproduce

Configure tests to use mysql
- php artisan test --parallel (too many connections)
- php artisan test (throws memory exception)

**Comment by jbrooksuk** [comment]
Disable Pulse in your tests. You can add `PULSE_ENABLED=false` in your `phpunit.xml` file.

**Comment by walterdis** [comment]
Hello.

I've already done that and the problem still persists

**Comment by timacdonald** [comment]
@walterdis can you run the following terminal command in your application and let me know the output.

```
composer outdated -- laravel/pulse | grep version
```

**Comment by jessarcher** [comment]
Have you configured a different database connection for Pulse but maybe pointing to the same MySQL server? It's the only reason I can think why Pulse's existence would increase the number of database connections.

**Comment by walterdis** [comment]
> @walterdis can you run the following terminal command in your application and let me know the output.
> 
> ```
> composer outdated -- laravel/pulse | grep beta
> ```

@timacdonald  Hello ;)

```
versions : * v1.0.0-beta6
latest   : v1.0.0-beta6
```

@jessarcher Hi, i have configured it to use Redis. I was hoping that when I did this, Laravel Pulse would start getting the data  through the worker and not open connections to the database all the time

**Comment by timacdonald** [comment]
@walterdis can you please upgrade to `v1.0.0-beta7` and see if that fixes your issue.

Please ensure that `PULSE_ENABLED` is set to `false` in your `phpunit.xml`.

**Comment by Andilutten** [comment]
This just happened to us in production...
Laravel pulse was using 150 / 150 DB connections while updating something in the pulse_aggregates table. 1.5 hours of outage..

**Comment by taylorotwell** [comment]
@Andilutten were you using Octane?

**Comment by Andilutten** [comment]
@taylorotwell Nope

**Comment by timacdonald** [comment]
@Andilutten could you provide information here on what your setup looks like?

What Ingest driver are you using?

Are you running on a single `pulse:work` command?

Do you know if the issue originated in the `pulse:work` command on a different thread or during a request?

**Comment by timacdonald** [comment]
@Andilutten could you also let me know which version of the `beta` you had installed at the time?

**Comment by timacdonald** [comment]
@walterdis if you have `PULSE_ENABLED=false`, do you still get the memory / db issues in your tests? Just trying to nail down where things could be falling apart in the tests.

**Comment by DaanTisg** [comment]
We have the same issue. Both Telescope and Pulse are disabled in the CI environment:

`PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 565248 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 56`

**Comment by DaanTisg** [comment]
For me the issue has been resolved by updating all composer packages. Here are the changed package versions. It may be of use to someone:

![afbeelding](https://github.com/laravel/pulse/assets/139455038/dbca0762-fe01-4254-8d21-cb20d19a395b)

**Comment by timacdonald** [comment]
Got some more PRs coming in that should help address the memory issues. Will likely tag them early next week. Still working on understanding the DB connection issues. If there is any additional information you think could be useful to help us replicate the issue, that would be amazing 🤘

**Comment by Andilutten** [comment]
@timacdonald 
I was using version v1.0.0-beta2

**Comment by tasarsu** [comment]
Hi, I have same issue here, tested with v1.0.0-beta5 and v1.0.0-beta7

There are 800 tests in my project, test are running on mysql, phpunit.xml file with PULSE_ENABLED as false. No redis. After 400 tests I get this error:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 266240 bytes) in .... each time in different file

**Comment by ngl5000** [comment]
I'm experiencing memory issues as well. my db is postgres. I have a command which loops over a dbf file ~70k rows and saves the data in two tables using updateorcreate. when i have pulse enabled the mem required goes from a starting point of ~40mb to 250mb. with pulse diabled mem stays ~ 40mbs through the entire process

**Comment by walterdis** [comment]
> Got some more PRs coming in that should help address the memory issues. Will likely tag them early next week. Still working on understanding the DB connection issues. If there is any additional information you think could be useful to help us replicate the issue, that would be amazing 🤘

@timacdonald Hi.
I've created a test project for the memory issue.

https://github.com/walterdis/pulse-test

**Comment by timacdonald** [comment]
Hey folks, I've had a potential breakthrough on the memory issue. Will have something new tomorrow.

In the meantime, @ngl5000 and @tasarsu, can you confirm if the issue exists on the latest beta when you have `PULSE_ENABLED` set to `false` in your PHPUnit.xml?

**Comment by timacdonald** [comment]
Hey folks,

The memory issue should be resolved with https://github.com/laravel/pulse/pull/250 and using the `'null'` Ingest driver.

This means that you can put a cap on the amount of memory Pulse will capture in it's buffer and also keep your tests fast by not requiring Pulse to actually write to the DB during tests - but keep it enabled to reflect production.

All ingesting is wrapped in `rescue` calls, so having it write to the database doesn't really serve much purpose in a testsuite IMO.

**Comment by timacdonald** [comment]
@Andilutten do you know what kind of load you application was under around that time?

Was it a substantial amount of requests per minute?

I'm thinking perhaps you had a lot of traffic and the `upsert` queries were locking each other out and you had enough traffic for it to be problematic.

For high-traffic applications we recommend the Redis driver for this reason.

I'm sorry again that this impacted your production app.

**Comment by walterdis** [comment]
> Hey folks,
> 
> The memory issue should be resolved with a buffer limit introduced in #250
> 
> The DB connection issue in testsuites will be resolved using the `'null'` Ingest driver introduced in #245
> 
> This means that you can put a cap on the amount of memory Pulse will capture in it's buffer and also keep your tests fast by not requiring Pulse to actually write to the DB during tests - but keep it enabled to reflect production.
> 
> All ingesting is wrapped in `rescue` calls, so having it write to the database doesn't really serve much purpose in a testsuite IMO.

Hello @timacdonald 

I've done a `composer update` but the package was not updated.
Tried `composer remove laravel/pulse` and `composer require laravel/pulse` too

What i`m doing wrong? 

Thanks

**Comment by timacdonald** [comment]
@Andilutten we will tag a release next week that should allow you to update. Will keep ya posted.

**Comment by timacdonald** [comment]
`v1.0.0-beta8` has been tagged which should introduce these fixes.

**Comment by ngl5000** [comment]
@timacdonald i ran the monthly upload with the new beta release and it worked great this time. Thank you!!

**Comment by walterdis** [comment]
It's working here as well.

Thanks! ;)

**Comment by timacdonald** [comment]
Great to hear!

**Comment by taghwo** [comment]
@tasarsu did the beta8 push fix your issue? Having same memory error as you commented. I have more than 800 test cases, it timesout with error:

```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 65536 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Support/ViewErrorBag.php on line 11
```

Laravel pulse version:
```
versions : * v1.0.0-beta8
latest   : v1.0.0-beta8
```

phpunit.xml
```
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="MAIL_MAILER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="TELESCOPE_ENABLED" value="false"/>
        <env name="PULSE_ENABLED" value="false"/>
    </php>
```

@timacdonald I don't know if I need to open another issue.

**Comment by timacdonald** [comment]
@taghwo I think I know what could be impacting your testsuite.

Could you try something for me to help confirm: would you search of all usages of the `AboutCommand::add` function and comment them out?

You should at least find them in the following files:

- `vendor/laravel/pulse/src/PulseServiceProvider.php`
- `vendor/livewire/livewire/src/LivewireServiceProvider.php`

That function has a memory leak that is likely impacting your testsuite. I've submitted fix / work around to the framework (https://github.com/laravel/framework/pull/49557).

**Comment by tasarsu** [comment]
Hi @taghwo and @timacdonald 
I have just tested beta 8, and all the tests were completed without any memory errors. Thanks for the fix.

**Comment by timacdonald** [comment]
Thank you so much for trying that out.

We'll merge the framework fix and encourage everyone to update to get the fix across the ecosystem.

I'll close this and we can track the framework PR.

**Comment by taghwo** [comment]
> @taghwo I think I know what could be impacting your testsuite.
> 
> Could you try something for me to help confirm: would you search of all usages of the `AboutCommand::add` function and comment them out?
> 
> You should at least find them in the following files:
> 
> * `vendor/laravel/pulse/src/PulseServiceProvider.php`
> * `vendor/livewire/livewire/src/LivewireServiceProvider.php`
> 
> Then could you try running the testsuite again and let me know if there is an improvement?
> 
> That function has a memory leak that is potentially impacting your testsuite. I've submitted fix / work around to the framework ([laravel/framework#49557](https://github.com/laravel/framework/pull/49557)).

@timacdonald Unfortunately after commenting those lines out I still get the memory issue. Uninstalling Laravel Pulse the test suite runs successfully.

**Comment by timacdonald** [comment]
@taghwo I've found another memory leak that could be casing the issue; this time in Livewire.

I've submitted a fix (https://github.com/livewire/livewire/pull/7677).

Could you please try commenting out the `AboutCommand::add` functions again in:

- `vendor/laravel/pulse/src/PulseServiceProvider.php`
- `vendor/livewire/livewire/src/LivewireServiceProvider.php`

and then opening the `vendor/laravel/pulse/src/PulseServiceProvider.php` and commenting out the line `$livewire->addPersistentMiddleware($app->make('config')->get('pulse.middleware', []));` as seen here: https://github.com/laravel/pulse/blob/32fb030ebf9679a30c373cada2905568d3cf818e/src/PulseServiceProvider.php#L170


Thank you again for helping out with this one.

**Comment by timacdonald** [comment]
I've also found another memory leak in the framework that could have been impacting you due to the introduction of Livewire.

Could you make sure to update to at least `laravel/framework` [v10.37.3](https://github.com/laravel/framework/releases/tag/v10.37.3) and try again (also with the above ideas).

**Comment by taghwo** [comment]
Will try these out over the weekend and get back on Monday.

**Comment by timacdonald** [comment]
@taghwo, Pulse now requires a minimum framework version of `10.34`. If your application has not yet updated to `10.34` or greater you will not be able to install the latest beta.

I recommend updating _at least_ to `10.37.3` to address the memory leak issue reported.

**Comment by taghwo** [comment]
Worked fine now. Thanks @timacdonald.

**Comment by RomkaLTU** [comment]
I have same issue, it's not resolved or re-apeared again. Memory leaks when running test everything is disabled in phpunit.xml.

Pulse version: beta15
Framework version: 10.48.2

**Comment by timacdonald** [comment]
@RomkaLTU, are you saying you are experiencing memory leaks in your testsuite on those versions?
