### ISSUE TITLE
PAge is not loading missing livewire.js

### ISSUE THREAD

**Issue by nezaboravi** [laravel/pulse#201]
### Pulse Version

1

### Laravel Version

10.35.0

### PHP Version

8.2

### Livewire Version

3

### Database Driver & Version

mysql

### Description

ON production site, with empty database entries, it does loading page.

IN dev console i see that livewire.js gives 404.
Now, this is weird, because the same code, works on dev server and on my local.

Now, maybe is worth to mention, i am running producion site via Forge as isolated site? Dont know if this can have any affects.

### Steps To Reproduce

NOthinf special here to reproduce it. As in my bug description. Happy to provide access to repo if needed.

**Comment by haugstrup** [comment]
I had the same issue and it was an nginx configuration issue. Go to edit your site's nginx configuration file and find the `# Cache expires headers` section near the bottom.

Immediately **before** that section insert this snippet to tell nginx to let your Laravel app handle requests for `livewire.js`

```
    location = /livewire/livewire.js {
        expires off;
        try_files $uri $uri/ /index.php?$query_string;
    }
```

**Comment by nezaboravi** [comment]
Thank you @haugstrup for reply and advise, but i am not confident to do that, as this is Laravel Forge provided server, same as my dev server, both forge provided, and works on dev, but not on live. Also works on local. The only difference is that Live server is created with isolation flag.

**Comment by jbrooksuk** [comment]
Please provide us with the exact version of Pulse you're running. v1.0.0-beta5 is currently the latest version, so check you're on that too.

**Comment by nezaboravi** [comment]
@jbrooksuk here
<img width="443" alt="image" src="https://github.com/laravel/pulse/assets/1515172/7cb2d954-4d91-4bf9-a1e9-1c5e144cac2a">

**Comment by jessarcher** [comment]
@nezaboravi Could you please provide the output of:

```sh
php artisan route:list --path=livewire
```

> Happy to provide access to repo if needed.

The repo would be helpful if you're able!

**Comment by timacdonald** [comment]
This is a known "issue" with Livewire.

See their docs...

<img width="771" alt="Screenshot 2023-12-11 at 11 13 42 am" src="https://github.com/laravel/pulse/assets/24803032/f9011643-60a7-4706-9bd0-5896089e15ed">

which links to: https://benjamincrozat.com/livewire-js-404-not-found

We are considering bundling Livewire into Pulse so that users do not need to consider or deal with this. For now, follow the above blogpost guide on configuring NGINX.

**Comment by timacdonald** [comment]
Opened a PR to address this moving forward: https://github.com/laravel/pulse/pull/266
