### ISSUE TITLE
Getting syntax error when I run migration on PostgreSQL

### ISSUE THREAD

**Issue by haroon-mahmood-4276** [laravel/pulse#202]
### Pulse Version

1.0@beta

### Laravel Version

10.32.1

### PHP Version

8.1.2-1ubuntu2.14

### Livewire Version

3.1.0

### Database Driver & Version

psql (PostgreSQL) 16.0 (Ubuntu 16.0-1.pgdg22.04+1)

### Description

I have followed the laravel/pulse documentation and When I run the migration after publishing the `config/pulse.php`, I got the following error:
![image](https://github.com/laravel/pulse/assets/70590766/7fd62436-b5b1-438c-8c05-fe19f64dc1b4)

Also, It didn't publish the migration.
![image](https://github.com/laravel/pulse/assets/70590766/17d42103-e781-4e93-9f98-a131184d97e8)

### Steps To Reproduce

Change the `composer.php`
 ```php
"minimum-stability": "beta",
"prefer-stable": true
```

Then install Laravel/Pulse
```php
composer require laravel/pulse
```

Then publish the Pulse configuration and migration files
```php
php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
```

Then run the migrate command
```php
php artisan migrate
```

**Comment by jbrooksuk** [comment]
Please can you provide us with the exact version of Pulse that you're running. Postgres support was added in [v1.0.0-beta4](https://github.com/laravel/pulse/releases/tag/v1.0.0-beta4).

**Comment by haroon-mahmood-4276** [comment]
> Please can you provide us with the exact version of Pulse that you're running. Postgres support was added in [v1.0.0-beta4](https://github.com/laravel/pulse/releases/tag/v1.0.0-beta4).

Sure, the exect Pulse version is v1.0.0-beta2

**Comment by jbrooksuk** [comment]
@haroon-mahmood-4276 please update to the latest version `v1.0.0-beta5`. If the issue persists, please re-open the issue.
