### ISSUE TITLE
php artisan vendor:publish --tag=pulse-config

### ISSUE THREAD

**Issue by arbazargani** [laravel/pulse#204]
### Pulse Version

1.0@beta

### Laravel Version

10.10

### PHP Version

8.1

### Livewire Version

3.2

### Description

just installed pulse onexisting laravel app, and /pulse route throws this error.

### Steps To Reproduce

fresh install of pulse on existing laravel app.
![image](https://github.com/laravel/pulse/assets/46598928/1dc21ba8-b35e-45e6-9fe6-6c72db340048)

**Comment by jbrooksuk** [comment]
Please update your `composer.json` file to a newer version of Laravel. The `Benchmark::value()` method was added in https://github.com/laravel/framework/pull/48077 and tagged for `v10.20`.
