### ISSUE TITLE
0% CPU usage on docker container

### ISSUE THREAD

**Issue by ariaieboy** [laravel/pulse#207]
### Pulse Version

1.0.0-beta5

### Laravel Version

10.x (latest)

### PHP Version

8.2 (latest)

### Livewire Version

3

### Database Driver & Version

Postgresql 16 on docker container

### Description

In a dockerized environment Laravel Pulse always reports 0% CPU usage.

### Steps To Reproduce

create a laravel project using Laravel Sail and check the CPU usage.

**Comment by ariaieboy** [comment]
Ok, I checked the source and found that pulse uses the `top` command to check the CPU usage.
The `top` command in my containers reports 0% CPU usage.
I use Alpine Linux as the base image.

**Comment by jbrooksuk** [comment]
It looks like this may be a limitation within `top`, that prevents it from being able to properly read CPU usage of virtualized resources. https://github.com/moby/moby/issues/26113

**Comment by ariaieboy** [comment]
> It looks like this may be a limitation within `top`, that prevents it from being able to properly read CPU usage of virtualized resources. [moby/moby#26113](https://github.com/moby/moby/issues/26113)

I didn't test this on other base images like Ubuntu but using `mpstat` I can get the CPU usage in my container.

**Comment by ariaieboy** [comment]
`/etc/os-release host machine`
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
`/etc/os-release container`
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.5
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

**Comment by jessarcher** [comment]
Interesting - that output is formatted quite differently from what we're expecting. Most notably, the CPU line begins with "CPU:" but Pulse is expecting it to begin with "%Cpu(s):".

Here's the output from `top` on my Linux laptop:

```
➜  ~ top -bn1
top - 08:48:45 up 3 days, 15:20,  2 users,  load average: 1.69, 1.36, 1.22
Tasks: 579 total,   1 running, 573 sleeping,   0 stopped,   5 zombie
%Cpu(s):  9.1 us,  4.5 sy,  0.0 ni, 86.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  31737.7 total,   1337.3 free,  17214.1 used,  15534.1 buff/cache
MiB Swap:   8192.0 total,   7779.7 free,    412.2 used.  14523.6 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
```

What version of `top` do you have?

On my host machine I have:
```
➜  ~ top -V
top from procps-ng 4.0.3
```

And in my Sail (Ubuntu) container I have:
```
sail@57830d912d37:/var/www/html$ top -v
  procps-ng 3.3.17
```

Interestingly, they both have a different CLI option for getting the version, but both follow the same format for the CPU line.

I'm guessing your version of `top` probably isn't the procps-ng version but rather an entirely different implementation that Alpine has chosen. The output looks more similar to the implementation Darwin ships with, although interestingly yours still supports the `-bn1` flags.

**Comment by ariaieboy** [comment]
@jessarcher yes the alpine uses BusyBox 1.36.1 for `top` command.

**Comment by jessarcher** [comment]
Hi @ariaieboy, I've created #236, which updates the parsing of the `top` output to hopefully work for both versions of `top` on Linux.

**Comment by ariaieboy** [comment]
@jessarcher Can we have this in a tagged release so I can test it on my instances?

**Comment by timacdonald** [comment]
`v1.0.0-beta8` has just been tagged.
