### ISSUE TITLE
Call to undefined method Illuminate\Support\Benchmark::value()

### ISSUE THREAD

**Issue by Jaspur** [laravel/pulse#208]
### Pulse Version

1.0.0-beta2

### Laravel Version

9.52.16

### PHP Version

8.2.12

### Livewire Version

3.0.0-beta.6

### Description

Getting this error when navigating to `/pulse`:

`Call to undefined method Illuminate\Support\Benchmark::value()`

### Steps To Reproduce

Install repo with Laravel V9

**Comment by crynobone** [comment]
Laravel Pulse can't be used with Laravel 9, please upgrade to Laravel 10
