### ISSUE TITLE
Is pulse supported in lumen ? 

### ISSUE THREAD

**Issue by pawan1793** [laravel/pulse#209]
I'm trying to integrate with lumen but getting following error 
php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
Unable to locate publishable resources.

**Comment by driesvints** [comment]
None of our first party packages support Lumen. Lumen isn't developed anymore either. Please switch to Laravel: https://laravelshift.com/convert-lumen-to-laravel
