### ISSUE TITLE
Migrate error on PostgreSQL

### ISSUE THREAD

**Issue by taghwo** [laravel/pulse#210]
### Pulse Version

1.0@beta

### Laravel Version

10.2

### PHP Version

8.1

### Livewire Version

N/A

### Database Driver & Version

PostgreSQL: 15.2

### Description

After publishing assets
`php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"`
when I ran `php artisan migrate` I got the error below

```bash
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
LINE 1: ...(16) not null generated always as (unhex(md5(`key`))), "valu...
                                                             ^ (Connection: pgsql, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, "key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }

      +35 vendor frames 

  36  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

From the docs it says PostgreSQL is supported? : `Pulse's first-party storage implementation currently requires a MySQL or PostgreSQL database.`

Side note: After publishing assets, the migration file was not copied to database/migrations

### Steps To Reproduce

composer require laravel/pulse
php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
php artisan migrate

**Comment by driesvints** [comment]
Thanks. Please let us know which beta you're using.

**Comment by taghwo** [comment]
> Thanks. Please let us know which beta you're using.

This is what I have it after running `composer require laravel/pulse` => "laravel/pulse": "^1.0@beta",

**Comment by taghwo** [comment]
> @taghwo we need to know the exact version installed, please. Can you run `composer why laravel/pulse` and let us know the output?

@jbrooksuk here `laravel/pulse (v1.0.0-beta2)`
