### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by asterism612** [laravel/pulse#213]
### Pulse Version

^1.0@beta

### Laravel Version

10.24.0

### PHP Version

8.2.6

### Livewire Version

none

### Database Driver & Version

postgresql 15

### Description

Error with migration : 

 Duplicate table: 7 ERROR:  relation "pulse_values" already exists (Connection: pgsql, SQL: create table "pulse_values" ("id" bigserial not null primary key, "timestamp" integer not null, "type" varchar(191) not null, "key" text not null, "key_hash" uuid not null generated always as (md5("key")::uuid) stored, "value" text not null))

### Steps To Reproduce

php artisan migrate

**Comment by asterism612** [comment]
I proceeded with no table, but I got the same error as above

**Comment by jessarcher** [comment]
What specific Pulse version are you using?

```
composer show laravel/pulse | grep versions
```

**Comment by driesvints** [comment]
Feel free to reopen this and provide the exact beta version, thanks

**Comment by PaulCordellier** [comment]
Hello, I am having an error that looks really similar. Here's the error that I got:

```
  Syntax error: 7 ERROR:  syntax error at or near "("
LINE 1: ...ull, "key_hash" uuid not null generated always as (md5("key"...
                                                             ^ (Connection: pgsql, SQL: create table "pulse_values"
("id" bigserial not null primary key, "timestamp" integer not null, "type" varchar(255) not null, "key" text not null,
"key_hash" uuid not null generated always as (md5("key")::uuid) stored, "value" text not null))

  10  database/migrations/2023_06_07_000001_create_pulse_tables.php:33
      Illuminate\Support\Facades\Facade::__callStatic() 

  36  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

I reproduced the installation steps from the documentation until `php artisan migrate`.

Laravel version : 10.40.0
PHP version : 8.1.13
Pulse version : v1.0.0-beta8
Postresql version : 11.18

`php artisan cache:clear` is not helping.

If you have any question about my project I'll try to answer them!

**Comment by timacdonald** [comment]
@PaulCordellier Pulse requires generated columns, which were introduced in Postgres 12.

Pulse is not currently compatible with your version of Postgres.

**Comment by PaulCordellier** [comment]
Unfortunately I can't upgrade the version because I have to use the server from my university. Thanks anyways, and have a good day!
