### ISSUE TITLE
How to change "id" in return \App\Models\User::whereKey($ids)->get(['id', 'name', 'email']); 

### ISSUE THREAD

**Issue by asterism612** [laravel/pulse#214]
### Pulse Version

1.0@beta

### Laravel Version

10.24.0

### PHP Version

8.2.5

### Livewire Version

none

### Database Driver & Version

pgsql

### Description

How to change "id"? 

return \App\Models\User::whereKey($ids)->get(['id', 'name', 'email']); 

i use uid instead of id

### Steps To Reproduce

..

**Comment by jessarcher** [comment]
Please see https://laravel.com/docs/10.x/pulse#application-usage-card for instructions :+1:
