### ISSUE TITLE
Laravel\Pulse\Recorders\CacheInteractions::shouldIgnore(): Argument #1 ($value) must be of type string, null given

### ISSUE THREAD

**Issue by filip-nifti** [laravel/pulse#215]
### Pulse Version

v1.0.0-beta6

### Laravel Version

10.35

### PHP Version

8.2

### Livewire Version

3.3

### Database Driver & Version

MySQL 8.0.35 ubuntu 0.22.04.1 (Laravel Forge)

### Description

I set up a Laravel pulse on our production and development server. I have a separate database in Laravel Forge for Pulse.
The config is entirely default, i have not modified anything.

**Stacktrace:**
`[2023-12-12 06:39:31] production.ERROR: Laravel\Pulse\Recorders\CacheInteractions::shouldIgnore(): Argument #1 ($value) must be of type string, null given, called in MySite/vendor/laravel/pulse/src/Recorders/CacheInteractions.php on line 50 {"exception":"[object] (TypeError(code: 0): Laravel\\Pulse\\Recorders\\CacheInteractions::shouldIgnore(): Argument #1 ($value) must be of type string, null given, called in MySite/vendor/laravel/pulse/src/Recorders/CacheInteractions.php on line 50 at MySite/vendor/laravel/pulse/src/Recorders/Concerns/Ignores.php:10)
[stacktrace]
#0 MySite/vendor/laravel/pulse/src/Recorders/CacheInteractions.php(50): Laravel\\Pulse\\Recorders\\CacheInteractions->shouldIgnore()
#1 MySite/vendor/laravel/pulse/src/Pulse.php(294): Laravel\\Pulse\\Recorders\\CacheInteractions->Laravel\\Pulse\\Recorders\\{closure}()
#2 MySite/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Laravel\\Pulse\\Pulse->Laravel\\Pulse\\{closure}()
#3 MySite/vendor/laravel/pulse/src/Pulse.php(294): Illuminate\\Support\\Collection->each()
#4 MySite/vendor/laravel/pulse/src/PulseServiceProvider.php(130): Laravel\\Pulse\\Pulse->store()
#5 MySite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(227): Laravel\\Pulse\\PulseServiceProvider->Laravel\\Pulse\\{closure}()
#6 MySite/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#7 {main}`

### Steps To Reproduce

Install pulse in laravel 10 project. Deploy on forge with MySQL-database hosted via forge.
Use the cache on the site.

**Comment by jessarcher** [comment]
Hi @filip-nifti,

The error message implies that you're reading a cache key of `null` - i.e. `Cache::get(null)`. Does that sound possible or is it definitely occurring with a string cache key?

I'll PR a fix to prevent the error with a null key.

**Comment by filip-nifti** [comment]
It might be possible that a parameter that is sent to one of the caching functions can be passed as null...
Will have to investigate and fix that.

Thank you for the fix and the quick response!

**Comment by jessarcher** [comment]
No worries! Feel free to open another issue if the issue still occurs once #216 is tagged.

**Comment by filip-nifti** [comment]
We are using TaggedCache in our project and that seems to have been removed from Laravels documentation, could that have anything to do with it or is it probably just a null value being passed to my function?
