### ISSUE TITLE
Card Carousel/Tab

### ISSUE THREAD

**Issue by wit3** [laravel/pulse#218]
A nice feature for card could be a card container like a carousel that allow to automatic change( or manually) based on time a list of children cards.

In a dashboard with size limited, the number of card shown its limited to size grid, with this feature a box 4x2 can hold many cards for example.

it's an idea ok or nah?

**Comment by jbrooksuk** [comment]
I think you could make a custom View component that wraps other components and provides the scroll you're after. You'd need some additional Tailwind classes though.

**Comment by timacdonald** [comment]
You can publish the dashboard and do whatever you would like with it.

Would you to publish the card as a package so others can use it.
