### ISSUE TITLE
RuntimeException During Application Tests

### ISSUE THREAD

**Issue by reppair** [laravel/pulse#225]
### Pulse Version

v1.0.0-beta6

### Laravel Version

v10.35.0

### PHP Version

8.2.13

### Livewire Version

3.3.0

### Database Driver & Version

mysql  Ver 8.1.0 for macos14.0 on arm64 (Homebrew)

### Description

When I run my application tests, while the database is being refreshed I get the following exception `RuntimeException: Unsupported database driver [sqlite].` Which is understandable considering the [documentation](https://laravel.com/docs/10.x/pulse#installation), namely:

> Pulse's first-party storage implementation currently requires a MySQL or PostgreSQL database. If you are using a different database engine, you will need a separate MySQL or PostgreSQL database for your Pulse data.

My point is, installing Laravel Pulse should not break the app tests, I guess. 🐛 

I got around it by updating the migration file and setting `PULSE_ENABLED=false` for testing.

```php
public function up(): void
{
    if (app()->environment('testing') && ! config('pulse.enabled')) {
        return;
    }
    
    ...
}
```

Cheers! 

### Steps To Reproduce

Install pulse on application having test suite using `sqlite` database connection set for testing.

**Comment by DaanTisg** [comment]
For most people this shouldn't be an issue I think as the tests are commonly ran using the same database software as the application is using.

**Comment by driesvints** [comment]
PULSE_ENABLED=false is twtg here

**Comment by reppair** [comment]
> PULSE_ENABLED=false is twtg here

I tried setting this for testing first. Given the migration is published to database/migrations (default when following the docs) it still tries to migrate it.

What am I missing?

@driesvints did you try your suggested solution before closing the ticket?

**Comment by driesvints** [comment]
I'm sorry all. Apparently it doesn't help indeed. Right now Pulse isn't compatible with sqlite which also means in test suites so it's best that you add a workaround manually like the above.

**Comment by reppair** [comment]
Don't get me wrong, not here to complain whatsoever.

Thank you and the entire team! For all the great things you put out there for us to use.

Cheers!
