### ISSUE TITLE
/pulse should return 404 if unauthorized

### ISSUE THREAD

**Issue by nickdekruijk** [laravel/pulse#237]
When the viewPulse gate fails the visitor gets a "403 THIS ACTION IS UNAUTHORIZED." message. Which of course makes sense but it also exposes that pulse actually exists. It would be better to return 404 not found instead or at least have the option to.

**Comment by jbrooksuk** [comment]
You may customize the Gate manually:

```php
use App\Models\User;
use Illuminate\Auth\Access\Response;
use Illuminate\Support\Facades\Gate;

Gate::define('viewPulse', function (?User $user = null) {
    return $user?->isAdmin
        ? Response::allow()
        : Response::deny('Not Found', 404);
});
```

**Comment by nickdekruijk** [comment]
Thanks @jbrooksuk !
```Response::deny('Not Found', 404);``` still returns 403 for some reason but replacing it with ```abort(404);``` works just fine!

**Comment by timacdonald** [comment]
@nickdekruijk You likely did not have the user parameter specified as "nullable", which means the authorization check fails before the gate is called.

e.g.

```diff
- Gate::define('viewPulse', function ($user) {
+ Gate::define('viewPulse', function ($user = null) {
    // ...
});
```
