### ISSUE TITLE
Server storage is filled with cache data

### ISSUE THREAD

**Issue by Hegabovic** [laravel/pulse#238]
### Pulse Version

1.0.0

### Laravel Version

10.4

### PHP Version

8.2

### Livewire Version

3.0.2

### Database Driver & Version

mysql 8

### Description

Pulse if filling the server with a lot of files and cached data for no obvious reason , this is causing the server to run out of space 
![image](https://github.com/laravel/pulse/assets/56083879/53bfc2c0-7a4b-4a28-97a7-3ccd34b9e2db)

![image](https://github.com/laravel/pulse/assets/56083879/1576c1b6-a5ca-42d5-9f3b-f0a8ebb5b45f)

### Steps To Reproduce

visit laravel pulse url (localhost:8000/pulse) and monitor the  storage/framework/cache/data directory , you will find that the content of this file is duplicated each refresh

**Comment by jessarcher** [comment]
Hi @Hegabovic, I'm not sure which specific beta version of Pulse you're on, so could you first please try the latest version of Pulse (`v1.0.0-beta7`), which will also require you to update to Livewire 3.2.

**Comment by Hegabovic** [comment]
hello , i'm using pulse version  >> v1.0.0-beta7 , and i find that these cache files are coming when i run the command `php artisan pulse:check` , this command fills the server with too many cache files until the server goes down eventually

**Comment by jessarcher** [comment]
Thanks. I can confirm the issue when using the `pulse:check` command with the file cache driver. The cache locks it creates have a 5-second expiry, but the file cache driver does not automatically purge expired entries as other cache drivers do.

We're revisiting how this works and will hopefully have an improved solution soon.

**Comment by jessarcher** [comment]
This should be fixed when #260 is merged and tagged.

**Comment by timacdonald** [comment]
`v1.0.0-beta8` has been tagged.

**Comment by andreasnij** [comment]
@jessarcher How much cache storage space is reasonable for Pulse to use? I'm using `v1.0.0-beta8` and after a week my cache folder is almost 1 GB already. And this is in an application without much activity.
