### ISSUE TITLE
Undefined array key "lazy" - on pulse dashboard

### ISSUE THREAD

**Issue by ssmavask** [laravel/pulse#239]
### Pulse Version

1.0.0

### Laravel Version

10.37.3

### PHP Version

8.3.0

### Livewire Version

3.0.0

### Database Driver & Version

MySql 8.0.30

### Description

right after installing an opening pulse dashboard i got this error 
Undefined array key "lazy".
![Screenshot (35)](https://github.com/laravel/pulse/assets/69591787/6def2ead-e1ca-40a5-9b5a-7e9a813c2eb0)
![Screenshot (36)](https://github.com/laravel/pulse/assets/69591787/621b7de8-a473-4d88-a73b-a7c7443622c3)

### Steps To Reproduce

this is a fresh install of Laravel pulse and i am getting this issue right on the dashboard of pulse without any modifications. 
currently this error happed on private repositor but if require i can provide the access or code for debugging.

**Comment by ssmavask** [comment]
this is my current composer.json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "guzzlehttp/guzzle": "*",
        "ixudra/curl": "^6.22",
        "laravel/framework": "^10.10",
        "laravel/jetstream": "^3.2",
        "laravel/pulse": "^1.0@beta",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "3.0",
        "spatie/laravel-medialibrary": "10.10.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.8",
        "barryvdh/laravel-ide-helper": "^2.13",
        "enlightn/enlightn": "^2.6",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "pestphp/pest": "^2.0",
        "pestphp/pest-plugin-laravel": "^2.0",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}

**Comment by jessarcher** [comment]
Looks like you need to upgrade your Livewire version

**Comment by ssmavask** [comment]
thanks 
i figured I was missing ^ in the version definition so i updated it to 
"livewire/livewire": "^3.0",
after which i running composer update and it then updated my livewire and pulse also and it fixed my problem. 
😊

**Comment by timacdonald** [comment]
Pulse now explicitly requires Livewire version `^3.2`, so this should be resolved in the later versions of Pulse.
