### ISSUE TITLE
Script JS not found

### ISSUE THREAD

**Issue by danilopinotti** [laravel/pulse#244]
### Pulse Version

v1.0.0-beta7

### Laravel Version

v10.37.3

### PHP Version

8.1

### Livewire Version

3.3.0

### Database Driver & Version

postgres:9

### Description

Hello!

When I install pulse with no additional config and try to open the path "/pulse", I face with empty Pulse screen.

At the console, I have a message saying the script JS was not found (404), but, when I try to open the script link, it works:

![image](https://github.com/laravel/pulse/assets/11338999/c469bce1-94dd-4ca3-b548-0b9f5d9f360c)

![image](https://github.com/laravel/pulse/assets/11338999/d517f004-b0bc-482b-b0ad-65e74e70d5c5)

I tried with Chrome and Firefox. Both didnt work

### Steps To Reproduce

I updated my app from L8 to L10 and just installed Pulse with `PULSE_DB_CONNECTION=pgsql` in the .env file

**Comment by jessarcher** [comment]
Hi, I'm not sure how to replicate this one. Are you able to replicate it on a fresh Laravel install? And then maybe incrementally add things from your app to track down the specific circumstance that's triggering it?

**Comment by jbrooksuk** [comment]
Can you try emptying your browser caches and trying again? It's strange that you can navigate directly to the script but the browser is unable to access it to be imported.

**Comment by danilopinotti** [comment]
> Can you try emptying your browser caches and trying again? It's strange that you can navigate directly to the script but the browser is unable to access it to be imported.

I tried cleaning the cache, using another browser, and using the anonymous tab. None worked.

**Comment by danilopinotti** [comment]
Another weird behavior: when I open the script page, the error keeps appearing:

![image](https://github.com/laravel/pulse/assets/11338999/da96f069-f6b1-45f3-bec4-645bc9c66d8c)

**Comment by danilopinotti** [comment]
I solved the problem.

The problem was basically with Nginx. I **removed** the following lines from the host configuration file and the problem stopped happening:

```conf
    # CSS and Javascript
    location ~* \.(?:css|js)$ {
        expires off;
        access_log off;
        add_header Cache-Control "public";
    }
```
