### ISSUE TITLE
Migration error on PostgreSQL 15

### ISSUE THREAD

**Issue by BorisWild** [laravel/pulse#246]
### Pulse Version

1.0.0-beta7

### Laravel Version

10.37.3

### PHP Version

8.2

### Livewire Version

3.3.0

### Database Driver & Version

PostgreSQL 15

### Description

I'm using Forge+DO for my dev servers.
If you run `php artisan migrate` with pgsql connection (PULSE_DB_CONNECTION=pgsql) you will have an error message:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
LINE 1: ...(16) not null generated always as (unhex(md5(`key`))), "valu...
                                                             ^ (SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, "key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))

Solution is to create tables, manually :

```
create function unhex(text) returns text language sql immutable strict as $$
  select encode(decode($1, 'hex'), 'escape')
$$;

create table pulse_values (timestamp integer not null, type varchar(255) not null, key text not null, value text not null, key_hash char(16) generated always as (unhex(md5(key))) stored);
```

And I had to do it for other tables too...

### Steps To Reproduce

Use Postgres for your database, install Pulse and run `php artisan migrate`...

**Comment by mackhankins** [comment]
Same issue on 14.

**Comment by BorisWild** [comment]
> Same issue on 14.  Pulse Beta 8. Oddly Postgres 13 works fine in dev env.

I've updated laravel to latest version and migration worked fine)

**Comment by mackhankins** [comment]
> > Same issue on 14.  Pulse Beta 8. Oddly Postgres 13 works fine in dev env.
> 
> I've updated laravel to latest version and migration worked fine)

Hmm.. I ended up having to create my triggers and stuff with a little help from GPT.
