### ISSUE TITLE
Make user Gravatar avatars opt-in or configurable

### ISSUE THREAD

**Issue by andreasnij** [laravel/pulse#253]
The external Gravatar service that Pulse uses to display user avatars is probably not compliant with EU privacy regulation (GDPR) without information about it in the application's privacy policy. In the current Pulse documentation it is easy to miss that Pulse uses Gravatar by default. I think it would be a good to make Gravatar use opt-in or more easily configurable than creating your own user resolver function.

**Comment by driesvints** [comment]
Feel free to attempt a PR, thanks 👍

**Comment by jessarcher** [comment]
It should be a little easier after #251.

I don't know much about GDPR or the concerns, but the information passed to Gravatar is just a SHA256 hash of the user's email address and the images are only requested on the Pulse dashboard, which should only be for admins/staff.
