### ISSUE TITLE
Migrate rollback/fresh error

### ISSUE THREAD

**Issue by ligne13** [laravel/pulse#254]
### Pulse Version

1.0.0-beta7

### Laravel Version

10.34.2

### PHP Version

8.2.13

### Livewire Version

Livewire included in Pulse

### Database Driver & Version

MySQL 8.0.32 via Laravel Sail

### Description

I have installed Pulse on different database via the PULSE_DB_CONNECTION and DB_DATABASE_PULSE variables.

When I run `php artisan migrate:fresh` I get this error when executing the create_pulse_tables migration :

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'pulse_values' already exists (Connection: pulse, SQL: create table `pulse_values` (`id` bigint unsigned not null auto_increment primary key, `timestamp` int unsigned not null, `type` varchar(255) not null, `key` mediumtext not null, `key_hash` char(16) character set binary as (unhex(md5(`key`))), `value` mediumtext not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

So I have to manually delete the Pulse tables to make this fresh migration working.

### Steps To Reproduce

Install Pulse on a different database.
Run php artisan migrate:fresh.

**Comment by driesvints** [comment]
This is a limitation of `php artisan migrate:fresh` which cannot be run on multiple connections.
