### ISSUE TITLE
Pulse installation with Livewire v2

### ISSUE THREAD

**Issue by shafiramaki** [laravel/pulse#256]
### Pulse Version

1.0.0-beta-5

### Laravel Version

10.4.1

### PHP Version

8.2

### Livewire Version

2.11

### Description

<img width="1221" alt="Screenshot 2023-12-21 at 22 17 00" src="https://github.com/laravel/pulse/assets/35919418/c378ba26-7182-407c-926a-aee5e19dc31a">

### Steps To Reproduce

Laravel pulse installation with livewire v2

**Comment by jbrooksuk** [comment]
Pulse requires Livewire 3.2 as a minimum.
