### ISSUE TITLE
Is it possible to publish the assets?

### ISSUE THREAD

**Issue by sunscreem** [laravel/pulse#263]
My Nginx config automatically caches and optimises assets, such as `livewire/livewire.js?id=e2b302e9`.

This means a route which fakes the assets being available there, such as the one pulse uses, returns a 404.

In other projects I've been able to run `php artisan livewire:publish` to work around this, but in Pulse this does nothing. Would this be an option going forward?

**Comment by jbrooksuk** [comment]
This is a dynamic route that is registered by Livewire and serves the `livewire.js` script. You may want to update your Nginx script to ignore this script from being cached / optimized.

**Comment by driesvints** [comment]
Thanks @jbrooksuk

**Comment by sinnbeck** [comment]
There is guide here: https://benjamincrozat.com/livewire-js-404-not-found

**Comment by sunscreem** [comment]
Thanks @jbrooksuk and @sinnbeck  - it's set by my hosting company so I was looking for a workaround to save having to go to them to start changing things. Thanks anyway.

**Comment by sinnbeck** [comment]
@sunscreem Just ran the publish method and it does not seem to work in livewire 3. So maybe ask on the livewire repo or make a pr to add it back?

**Comment by timacdonald** [comment]
Opened a PR to address this moving forward: https://github.com/laravel/pulse/pull/266
