### ISSUE TITLE
Not picking up published view

### ISSUE THREAD

**Issue by scottmetoyer** [laravel/pulse#265]
### Pulse Version

1.0.0-beta8

### Laravel Version

10.39.0

### PHP Version

8.2

### Livewire Version

3.3.5

### Description

Pulse doesn't appear to pick up my changes in the published view.

I've published the view to resources/views/vendor/pulse/dashboard.blade.php, however none of the changes I make to that file appear on /pulse even after clearing all caches and views. What am I doing wrong?

### Steps To Reproduce

Publish views with: 

`php artisan vendor:publish --tag=pulse-dashboard`

Edit the published view by removing a component.

Clear caches with:

`php artisan optimize:clear`

Browse to /pulse. The component is still there.

**Comment by jessarcher** [comment]
Hi @scottmetoyer,

I'm afraid I can't replicate this one. How are you serving your application? Do you have something like opcache or Octane that might be caching things?

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
