### ISSUE TITLE
Problem with multiple guards

### ISSUE THREAD

**Issue by fscaringi** [laravel/pulse#269]
### Pulse Version

1.0.0-beta8

### Laravel Version

10.8

### PHP Version

8.2.0

### Livewire Version

3.0.2

### Description

Good morning,

I am writing to ask you about a problem. I set up a Laravel as Back End and I have three types of authentication. In config/auth I set these guards:
- user
- teachers
- administrator

Each of these is associated with a model:
- User
- Teacher
- Administrator

And therefore there are 3 tables in the DB:
- users
- teachers
- administrators

By setting Laravel Pulse all events are tracked correctly perhaps because "user" is the default guard.

For example, if a "teacher" logs in (with ID 5) it is shown on the Pulse dashboard that the "user" with ID 5 was logged in.

I would like to understand if it is possible to use Laravel Pulse in this case with multiple guards on multiple tables. I read about a similar case here on GitHub but perhaps reference was made to multiple types of users but always on the same table.

Thanks so much to anyone who wants to help me!

### Steps To Reproduce

Install Laravel Pulse and then open de dashboard with /pulse

**Comment by jessarcher** [comment]
Hi @fscaringi,

You will need to create a class that implements [`\Laravel\Pulse\Contracts\ResolvesUsers`](https://github.com/laravel/pulse/blob/1.x/src/Contracts/ResolvesUsers.php) and bind it in the container so you can control how users are captured and resolved.

To see the default implementation, you can look at [`\Laravel\Pulse\Users`](https://github.com/laravel/pulse/blob/1.x/src/Users.php). You can also check out an example in the tests [here](https://github.com/laravel/pulse/blob/792e600f70a2c60f05079d628d49d36d076e69cb/tests/Feature/PulseTest.php#L135-L167).

You'll want the `key` method to return a string that uniquely identifies the user across your guards/models. It could be something simple like `users:123` or even a JSON-encoded tuple like `json_encode([$user::class, $user->getAuthIdentifier()])`.

For resolving users, you'll need to make sure your `find` method handles the key format you've chosen and returns an object with `name`, `extra`, and `avatar` properties. You can perform the database query directly in the `find` method and make the `load` method do nothing, but if you want to avoid individual queries for each user, you can add some logic to the `load` method that accepts a collection of keys and groups them by model before querying. You'll want to hold them in a property on the class in a way that you can retrieve them by key with the `find` method.

It's important to note that for seven days, you will still have records in your Pulse database with the old key format, which is just the ID. You may choose to wipe these records and start fresh or make sure your `load` and `find` methods can also handle the old format. Given that the current data has no way to distinguish between models, you might be best just clearing your Pulse tables and starting fresh.

I hope that helps! Let me know if any questions.
