### ISSUE TITLE
Auth guard is ignored for user_request

### ISSUE THREAD

**Issue by ifrond** [laravel/pulse#270]
### Pulse Version

1.0.0@beta8

### Laravel Version

10.39.0

### PHP Version

8.1.4

### Livewire Version

3.0.2

### Database Driver & Version

Mysql 8.0

### Description

If you have different auth guards, only default is using for all types of guards.

### Steps To Reproduce

1. Create Model Admin with table and fields name, email, password, remember_token
2. in config/auth.php to 'guards' add 
'admin' => ['driver' => 'session','provider' => 'admin',],
to 'providers' add 'admin' => ['driver' => 'eloquent','model' => App\Models\Admin::class,],
3. try to login as `admin` and as `user`, only id of authed will be recorded to table pulse_entries, used guard will be ignored

**Comment by jessarcher** [comment]
Hey @ifrond, please see https://github.com/laravel/pulse/issues/269#issuecomment-1883986060 for information on capturing and resolving users when the ID alone is not sufficient.
