### ISSUE TITLE
When logged in, Application usage card does not show name and avatar.

### ISSUE THREAD

**Issue by taghwo** [laravel/pulse#272]
### Pulse Version

1.0.0-beta8

### Laravel Version

10.4

### PHP Version

8.1

### Livewire Version

3.02

### Database Driver & Version

PostgreSQL: 15.2

### Description

On my local set up. When I am logged into my app and I visit '/pulse', the Application usage card shows the counts with no name, email and avatar. 
On logging out from the app and I visit '/pulse' I see all the information. 
Is this normal? 

<img width="1132" alt="Screenshot 2024-01-10 at 14 58 44" src="https://github.com/laravel/pulse/assets/40868373/5db456b2-2cc7-4cd8-8566-6f0c5937491e">

This is how I am resolving the user:
```
  Pulse::user(fn ($user) => [
            'name' => $user->full_name,
            'extra' => $user->email,
            'avatar' => ""
  ]);
```

### Steps To Reproduce

Set up Laravel Pulse.
Login into your app, visit some pages.
Navigate to /pulse page. 
I cannot see name or email except I logout of the app and visit /pulse again then I see the information.

**Comment by timacdonald** [comment]
@taghwo could you please add some logging code around this, as it feels like it could be some application logic issue on this one.

Use the following resolver, which will log the users's data, allowing us to see which direction to look into the issue.

```php
Pulse::user(function ($user) {
    info('Resolving user', $data = [
        'name' => $user->full_name,
        'extra' => $user->email,
        'avatar' => "",
    ]);

    return $data;
});
```

**Comment by taghwo** [comment]
> @taghwo could you please add some logging code around this, as it feels like it could be some application logic issue on this one.
> 
> Use the following resolver, which will log the users's data, allowing us to see which direction to look into the issue.
> 
> ```
> Pulse::user(function ($user) {
>     info('Resolving user', $data = [
>         'name' => $user->full_name,
>         'extra' => $user->email,
>         'avatar' => "",
>     ]);
> 
>     return $data;
> });
> ```

@timacdonald here is what I got in the logs

```
[2024-01-11 09:56:37] local.INFO: Resolving user when logged in 
{"name”:”Taghwo Test”,”extra”:”tagwho+resellers@gmail.com","avatar":""} 

 [2024-01-11 09:57:34] local.INFO: Resolving user when not logged in 
 {"name”:”Taghwo Test”,”extra”:”tagwho+resellers@gmail.com","avatar":""} 
```

**Comment by timacdonald** [comment]
@taghwo are you seeing any errors in the browsers console window?

Can you view the HTML and see if the text is there but hidden?

Our built CSS is currently outdated, so I'm wondering if this is somehow an issue, but I don't know how it would impact this specifically.

**Comment by taghwo** [comment]
@timacdonald No error in the console.

What I have seen so far;

When authenticated:

In user-card.blade.php component, when I print the $user object I get the raw data(instance of User model) below, which has fields that cannot be parsed in the component

```json
{
"id":2314,
"first_name”:”John”,
”last_name”:”Doe”,
”email”:”johndoe+reseller@gmail.com",
"profile_image_url":"https:\/\/www.gravatar.com\/avatar\/5f825724ecd44523a4a2a27e154437bd"
}
```

In Usage.blade.php, when I print $userRequestCount->user, I get the resolved user information(name, extra, avatar) matching what is expected in user-card.blade.php component.  

When unauthenticated:
In user-card.blade.php component, when I print the $user object , it matches the resolved user information (name, extra, avatar).

So when I am logged in, it looks like something overrides the fields in $user object that is read in user-card.blade.php

**Comment by timacdonald** [comment]
@taghwo are you binding a custom `ResolvesUsers` contract? How are you binding the resolver? can you please share it?

Can you show me any customizations you have done to pulse in your service provider, i.e., any interactions with the `Pulse` facade?

**Comment by taghwo** [comment]
> @taghwo are you binding a custom `ResolvesUsers` contract? How are you binding the resolver? can you please share it?
> 
> Can you show me any customizations you have done to pulse in your service provider, i.e., any interactions with the `Pulse` facade?

@timacdonald No binding implementation of `ResolvesUsers` Contract. My AppServiceProvider has a lot of code in it already, so I created a custom service provider and I have the boot method looking like below:

```php
public function boot(): void
    {
        // Define a custom callback for user resolution
        Pulse::user(fn ($user) => [
            'name' => $user->full_name,
            'extra' => $user->email,
            'avatar' => '',
        ]);

        // Log exception for Pulse
        Pulse::handleExceptionsUsing(function (Exception $e) {
            Log::debug('An exception happened in Pulse', [
                'message' => $e->getMessage(),
                'stack' => $e->getTraceAsString(),
            ]);
        });
    }
```

Then registered the service provider in app.php

**Comment by timacdonald** [comment]
I see. Unfortunately I'm not able to replicate this behaviour.

Can you please create a minimal reproduction for this and we take a closer look?

```
laravel new bug-report --github="--public"
```

**Comment by taghwo** [comment]
> laravel new bug-report --github="--public"

@timacdonald Think I found the issue in my code base.

There is a View Composer that loads the auth user like below

```php
   Facades\View::composer('*', function (View $view) {
            if (Auth::check()) {
                    $view->with('user', Auth::user());
            }
   });
```
What would be the safest check to not force this user when on the pulse page. 
I modified the check to look something like

```php
Facades\View::composer('*', function (View $view) {
if (Auth::check() && ! Route::is('livewire.update')) {
```
It works but I am not sure if this is the safest approach to this.

**Comment by timacdonald** [comment]
I'd probably change the logic to only add the default user variable for views that don't already have a `$user` variable.

```php
View::composer('*', function ($view) {
    if (Auth::check() && ! isset($view['user'])) {
        $view->with('user', Auth::user());
    }
});
```

Doing route checking could work. You might also need to check if it is the `/pulse` route.
