### ISSUE TITLE
can not migrate with postgresql 

### ISSUE THREAD

**Issue by NajeebAskar** [laravel/pulse#275]
### Pulse Version

1.0@beta

### Laravel Version

9.52.16

### PHP Version

8.1

### Livewire Version

3.0

### Database Driver & Version

POSTGRESQL 13,14,15 

### when run php artisan migrate, get the following error:

```bash

 SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: ...) not null generated always as (unhex(md5(`key`))), "value" ...
                                                             ^ (SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, 
"key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))
 

### Steps To Reproduce

after install the package, use php artisan migrate when using PostgreSQL database.

**Comment by crynobone** [comment]
Laravel Pulse doesn't support Laravel 9, please upgrade to Laravel 10 to fix this issue.

**Comment by jessarcher** [comment]
Additionally, that looks like the MySQL syntax for creating the `pulse_values` tables, so I'm assuming you don't have the latest version of Pulse (`v1.0.0-beta9`) either.

**Comment by av3nger** [comment]
I have the same issue.
Laravel 10.28
PHP 8.2
PostgreSQL 15
