### ISSUE TITLE
Gate on local env returns 403 when not authenticated.

### ISSUE THREAD

**Issue by taghwo** [laravel/pulse#280]
### Pulse Version

1.0.0-beta8

### Laravel Version

10.4

### PHP Version

8.1

### Livewire Version

3.02

### Database Driver & Version

PostgreSQL: 15.2

### Description

This [comment](https://github.com/laravel/pulse/issues/75#issuecomment-1850996957) and in the documentation I can see the viewlPulse middleware should work without authentication when APP_ENV is set to "local". 
This is not the case for me. 

In my AuthServiceProvider I have.

```php
Gate::define('viewPulse', function (?User $user = null) {
                return $user?->isAdmin();
            });
```
I get a 403 page still when my APP_ENV is set to local. 
Telescope works without authentication when APP_ENV is set to local in the same code base.

Here are my middlewares in pulse.php

```php
'middleware' => [
        'web',
        Authorize::class,
    ],
```

PS: it works fine when I remove the Gate when APP_ENV is set to local.

### Steps To Reproduce

1. Set up Laravel Pulse in codebase.
2. Set APP_ENV to local.
3. Add gate to AuthServiceProvider as stated in [docs](https://laravel.com/docs/10.x/pulse#dashboard-authorization)
4. Try to access '/pulse'
5. It should return a 403

**Comment by timacdonald** [comment]
Hi @taghwo,

That comment is regarding the _default_ gate that ships with Pulse.

When you added the `viewPulse` gate to your application's service provider you overrode the _default_ gate, so that comment no longer applies.

```php
Gate::define('viewPulse', function (?User $user = null) {
    return $user?->isAdmin();
});
```

If you want it to always be:

- Accessible always in local
- Only accessible when admin in other environments

You would want the following...

```php
Gate::define('viewPulse', function (?User $user = null) {
    if (App::environment('local')) {
        return true;
    }

    return $user?->isAdmin();
});
```

I hope this helps.

**Comment by nastoychev** [comment]
> Hi @taghwo,
> 
> That comment is regarding the _default_ gate that ships with Pulse.
> 
> When you added the `viewPulse` gate to your application's service provider you overrode the _default_ gate, so that comment no longer applies.
> 
> ```
> Gate::define('viewPulse', function (?User $user = null) {
>     return $user?->isAdmin();
> });
> ```
> 
> If you want it to always be:
> 
> * Accessible always in local
> * Only accessible when admin in other environments
> 
> You would want the following...
> 
> ```
> Gate::define('viewPulse', function (?User $user = null) {
>     if (App::envionment('local')) {
>         return true;
>     }
> 
>     return $user?->isAdmin();
> });
> ```
> 
> I hope this helps.

Please fix in your comment `envionment` => `environment`

**Comment by nastoychev** [comment]
@timacdonald typo envionment => environment

**Comment by timacdonald** [comment]
Updated. Thanks

**Comment by Zen0x7** [comment]
@timacdonald there are a way to update this on docs?

Actually, we need to find your comment to fix this issue.
