### ISSUE TITLE
Record average data in time-related metrics

### ISSUE THREAD

**Issue by aryehraber** [laravel/pulse#281]
Hi team,

Firstly, thank you so much for building Pulse -- it's SO good, you smashed it out of the park!

I was inspecting our Pulse dashboard today and noticed that a few of the time-related metrics, like Slow Jobs, Slow Requests, Slow Queries & Slow Outgoing Requests, were running a little long but couldn't tell whether these were outliers or the norm. 

![Screenshot 2024-01-17 at 14 09 49](https://github.com/laravel/pulse/assets/5065331/a279da03-97f2-4426-9971-ab0421da6b30)

Having an "average" metric next to count and slowest would allow me to see whether all jobs/requests of that kind are slow or just a small amount — potentially making the issue less severe.

What are your thoughts on this? I'd be happy to try and submit a PR if you are open to it. Thanks!

**Comment by timacdonald** [comment]
Hi @aryehraber, we agree this could be a nice addition to Pulse 👍
