### ISSUE TITLE
top not Found

### ISSUE THREAD

**Issue by adityaa-codes** [laravel/pulse#286]
### Pulse Version

v1.0.0-beta9

### Laravel Version

10.40

### PHP Version

8.3

### Livewire Version

3.2

### Description

Inside my docker container, it says top not found
i;ve attached my Dockerfile, Logs Screenshot
![image](https://github.com/laravel/pulse/assets/26678129/e9776316-aeed-4892-ae54-336b66ab6182)
![image](https://github.com/laravel/pulse/assets/26678129/3cf3305d-a3d4-4cb0-8c3d-9a605a0b89c5)
![image](https://github.com/laravel/pulse/assets/26678129/3eef8bc0-6480-466c-8cde-7b73ecb7d158)

i read the previous issue,it wasn't helpful for me, raising it again
any resource/help would be awesome, thanks a ton

### Steps To Reproduce

Build app docker image
run container for pulse using docker-compose

**Comment by jbrooksuk** [comment]
Please install `top` by running `apt-get install procps`. Most Linux distributions have this installed by default, but occasionally a Docker image will not install it for space.

**Comment by adityaa-codes** [comment]
php-fpm doesnt come with top, so i modified my Dockerfile to install procps package and now the pulse is working
