### ISSUE TITLE
Exception throttling cache keys are shown

### ISSUE THREAD

**Issue by rndb8418** [laravel/pulse#291]
### Pulse Version

1.0.0.beta11

### Laravel Version

10.42.0

### PHP Version

8.2.9

### Livewire Version

3.4.0

### Description

The exception throttling keys are by default being hashed using MD5, which results in a 32 character string. These are shown in the cache stats in Pulse as it does not match any of the default exclusions (one being a 40 character string).

This can be toggled off to make the exception throttler use non-hashed keys, which does result in it being excluded. However this is undocumented it seems:

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L102

This is where the hashing takes place:

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L360

Suggestions:

1. Document that when using pulse, the developer may want to disable the MD5 hashing for exception throttling
2. Change the hash to result in a 40 character string
3. Or, include 32 character strings in the default exclusions
4. Or, prefix the hashed key with `illuminate:` (to be covered by other current exclusions)

### Steps To Reproduce

This is the default behaviour as `hashThrottleKeys` is `true`. Any exception raised that is not covered by don't report exclusions should trigger this currently.

**Comment by jessarcher** [comment]
I'm open to excluding 32-character hexadecimal strings by default, but I don't really like the existing 40-character exclusion we currently have, as it could have false positives.

My preference would be that all framework cache keys be prefixed (after any hashing) so they can be more easily identified. However, this would be a bit of a breaking change as it would effectively reset those keys when deployed. We could potentially add some temporary code that checks for the old key format if the new key format isn't found, and then later remove it once everyone has had a decent chance to be on the new key format only.

**Comment by rndb8418** [comment]
Perhaps the simplest solution for now is to add a note of the `hashThrottleKeys` in the pulse documentation so users of Pulse can choose if they want to toggle it or exclude it? It took me a while to identify where these hashed cache keys were coming so may help others in future.

As we would need to make the change for the hashing/prefix in the `laravel/framework` repo, perhaps that could be added for v11 and made note of in the upgrade guide?

**Comment by timacdonald** [comment]
As this isn't specifically a Pulse issue, I'm going to close this. I do think we need to work on the frameworks cache key prefix idea, but for now Pulse is working as expected here - even if it isn't lovely to look at.
