### ISSUE TITLE
Add time period when cleaning data

### ISSUE THREAD

**Issue by paulo-hortelan** [laravel/pulse#294]
I'm not sure if this feature already exists, but I would like to delete old data from all my pulse tables. I've checked on the documentation and source code and looks like there is only this command:

- `php artisan pulse:clear` with the options `--type and --force`. 

This way you can delete all the data or only a specific type.

Can we improve the command with another option so It can delete old data based on the `bucket` column of `pulse_aggregates` table and the  `timestamp` of the `pulse_entries`? It would become something like this

```
pulse:clear {--type=* : Only clear the specified type(s)}
            {--force : Force the operation to run when in production}
            {--period=* : Only clear the specified period (days, weeks, months)}
```

If It makes sense I would happily send a PR with this feature 😁

**Comment by jessarcher** [comment]
I'm open to the idea. Can you explain more about the use case for deleting the data? Pulse automatically deletes records once they're no longer required for any of the time periods in the dashboard. The main reason we allow deleting specific types is for when you change the configuration for a metric in a way that makes the existing data pollute new data coming in. For example, if you change the sample rate.

**Comment by paulo-hortelan** [comment]
I didn't know that Pulse automatically deletes old records, is that on the documentation? 

The use case was to schedule this command to clear old data but it's no longer necessary since it automatically does it.

Also, there is an option to add or remove time periods on the dashboard? Let's say I want to see my data on the last month, can I do that?

**Comment by timacdonald** [comment]
@paulo-hortelan we don't currently support changing the time periods, but it isn't off the cards.

Will close this as it is more of a feature request than an issue.
