### ISSUE TITLE
Support for autoscaled services

### ISSUE THREAD

**Issue by markwalet** [laravel/pulse#295]
I've seen [some discussion](https://www.reddit.com/r/laravel/comments/18od4hk/comment/keoykmo/?utm_source=share&utm_medium=web2x&context=3) on Reddit about using Pulse in a multi-container environment. The problem is that autoscaled services would quickly result in a big list of stale servers. Which isn't desirable IMO.

Let try to find a way to improve this. I'm not sure what the "correct" solution would be in this case. I just want to put down some ideas. The first three are from the reddit post of Tim MacDonald.

1. We could add a “stale after” config to allow you to only show servers that have responded after a given time.
2. Have servers only show up if there is data for them in the given window, e.g., 1hr, 6hr, etc. this is kinda risky however as your server might have been offline for an hour and that might be a critical issue.
3. We could collapse the non-responsive servers into an expandable section.
4. We could allow for a non-unique server name. And aggegrating into averages when multiple values get sent.
5. We could add an "is autoscaled" option to the server configuration and add an extra unique ID for all subtasks of that specific server. Keeping the server_name the same across deployments and removing the "stale" servers when this flag is enabled.

One thing to keep in mind is that it would be preferable to keep insights in our dashboard across multiple deployments. So you could see a historical view of your server statistics and determine if your new deploy had any memory/cpu implications.

If there are other ideas on how this can be tackled, please let me know. I don't think there's an obvious solution for this use-case but I do think we should have some kind of support for it because I think it's a reasonably common server configuration.

Many thanks for the great product and keep up the good work. See you guys at Laracon EU :)

**Comment by timacdonald** [comment]
Hey there,

Although I agree there are some potential improvements we could make here for these situations, I'm going to close this as it isn't an issue and is really a feature request.

Hope you enjoyed LaraconEU. I had a blast!

**Comment by timacdonald** [comment]
Looks like we have a PR attempting to address this one: https://github.com/laravel/pulse/pull/316
