### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by jean-mathieu-myevent** [laravel/pulse#298]
### Pulse Version

v1.0.0-beta11

### Laravel Version

v10.42.0

### PHP Version

8.2

### Livewire Version

v3.4.2

### Database Driver & Version

MySQL 8.0.30

### Description

As soon as I add:
```
    'recorders' => [
    ] 
```

In the pulse.php config file. I get this error:
`Trying to access array offset on value of type null`

### Steps To Reproduce

1. Open pulse.php config file
2. Add `recorders' => []`
3. You should be getting an error.

I'm using the default configuration for Pulse same for the Pulse dashboard

**Comment by jessarcher** [comment]
Hi @jean-mathieu-myevent, may I ask why you're adding that?

I assume the error appears when loading the dashboard, which would be because the cards can't load their configuration.

**Comment by jean-mathieu-myevent** [comment]
> Hi @jean-mathieu-myevent, may I ask why you're adding that?
> 
> I assume the error appears when loading the dashboard, which would be because the cards can't load their configuration.

Initially I was trying to implement this:
https://github.com/maantje/pulse-database

But as soon as I added it in the recorders array it was given this error. So when attempting to debug, I noticed by just adding the array even while being empty it would give that error.

**Comment by timacdonald** [comment]
This issue only arises on the dashboard when you are using cards that do not have their recorders registered.

I would recommend making sure all cards you reference in your dashboard have their appropriate recorders added.
