### ISSUE TITLE
Application Usage card throws 500

### ISSUE THREAD

**Issue by asamofal** [laravel/pulse#300]
### Pulse Version

1.0.0-beta11

### Laravel Version

10.42.0

### PHP Version

8.2.13

### Livewire Version

3.4.4

### Database Driver & Version

MySQL

### Description

Application Usage card stopped working after the update from beta7 to beta11.

```
[2024-01-30 10:00:12] production.ERROR: Undefined property: stdClass::$id {"view":{"view":"/var/www/vendor/laravel/pulse/resources/views/livewire/usage.blade.php","data":[]},"userId":"01g512gg5pqbzjncpdsepk6nbp","exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Undefined property: stdClass::$id at /var/www/vendor/laravel/pulse/resources/views/livewire/usage.blade.php:53)

[previous exception] [object] (ErrorException(code: 0): Undefined property: stdClass::$id at /var/www/storage/framework/views/5ecb34298cf4b6b02c0ac901429d166c.php:137)
```

 I tried to delete all the records with `user_request` but it didn't help.
```sql
DELETE FROM pulse_aggregates WHERE type = 'user_request';
DELETE FROM pulse_entries WHERE type = 'user_request';
```
Config has a default state.
```
Recorders\UserRequests::class => [
            'enabled' => env('PULSE_USER_REQUESTS_ENABLED', true),
            'sample_rate' => env('PULSE_USER_REQUESTS_SAMPLE_RATE', 1),
            'ignore' => [
                '#^/pulse$#', // Pulse dashboard...
            ],
        ],
```

Probably something wrong with resolving users but I'm not sure. Any ideas? 🙄

### Steps To Reproduce

-

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by sinnbeck** [comment]
@asamofal Curious where you have `->id` in that file. It is nowhere in the original file
https://github.com/laravel/pulse/blob/1.x/resources/views/livewire/usage.blade.php

Did you manually alter it in the vendor folder?

**Comment by asamofal** [comment]
@driesvints With all due respect, if I do all of your steps probably I can figure out the problem myself, not confident that I have so much time to jump so deep into this...

@sinnbeck This is the most interesting part, of course, no, the vendor folder is unattached. I don't even have anything special, just installed one extra package for pulse - [laravel-pulse-schedule](https://github.com/hosmelq/laravel-pulse-schedule) but I don't think it's related to the issue, the problem with `Recorders\UserRequests`. 
I use ULIDs as `id` in `users` table but it shouldn't be a problem because I see user ids in pulse's tables.

And again it happened after the update from beta7 to beta11. I checked the changelog but not found anything related to UserRequests recorder, therefore I'm so confused...

**Comment by sinnbeck** [comment]
@asamofal Did you check the file on the server? Or try clearing it if its perhaps an old version `php artisan view:clear`

**Comment by asamofal** [comment]
@sinnbeck `php artisan view:clear` did the trick 🤔 But I've tried `artisan cache:clear` before and was so confident that this includes clearing all the cache types, isn't?

**Comment by driesvints** [comment]
@asamofal no that's just the application cache
