### ISSUE TITLE
Queued listener on secondary queue is also being displayed on the default queue graph under 'Queues' card

### ISSUE THREAD

**Issue by Winger15mk** [laravel/pulse#305]
### Pulse Version

1.0.0-beta11

### Laravel Version

10.43.0

### PHP Version

8.2

### Livewire Version

3.2.0

### Description

When a queued listener is triggered on a secondary queue, it is also showing within pulse as queued on default as well. The secondary queue jobs process perfectly and show as the purple processed line, however the line remains in the default queue. Horizon shows all outstanding jobs completed. Looking at the database pulse_aggregates table I see the duplicate records being created despite the technical processing working as expected.

### Steps To Reproduce

- Triggered a queued listener on a secondary queue to default using the ShouldQueue implementation. Define the queue within the listener itself (public $queue = 'secondary_queue';)
- Pulse shows both the secondary queue and default queue graphs both with a spike displaying queued jobs, whereas should only show in the secondary.

**Comment by Winger15mk** [comment]
<img width="386" alt="Screenshot 2024-02-06 at 20 54 00" src="https://github.com/laravel/pulse/assets/11196158/07d46d41-78ce-4a0f-9436-36b635c8dcb8">

Visual example of the issue

**Comment by timacdonald** [comment]
@Winger15mk, we have seen this before and it has been a configuration issue.

Could you please provide your `config/queue.php` file for us to have a look at?

**Comment by Winger15mk** [comment]
[queue.txt](https://github.com/laravel/pulse/files/14240618/queue.txt)

Note that I set queue connection to Redis in env

**Comment by timacdonald** [comment]
Thanks. Looks like this is actually a Pulse issue, not a config issue as I first expected.

Should be fixed with https://github.com/laravel/pulse/pull/313

Will close this and we can follow along with the PR.
