### ISSUE TITLE
Feature request: Ignore slow jobs for a specific queue

### ISSUE THREAD

**Issue by markwalet** [laravel/pulse#306]
I have a single queue configured for jobs that take a bit more time. Ideally I would be able to ignore all these jobs from the slow job recorder. Setting a separate threshold per queue would also work.

Is this something you'd like in the pulse package? Or should this be an optional (third party) extension?

**Comment by jessarcher** [comment]
Can you just add ignore patterns for the known slow jobs that you don't want to see? Ignoring an entire queue seems a little broad.

**Comment by markwalet** [comment]
That's definitely possible. I'm doing this right now.

Maybe ignoring a complete queue would not be the preferred solution here. But at least being able to set the threshold per queue would be very helpful. We can already specify the timeout per queue, so in my opinion it makes sense to have a similar level of configuration on the thresholds in Pulse. What do you think?

**Comment by timacdonald** [comment]
Until we have more demand for something like this I would recommend using the `Pulse::filter` method to achieve this.

In the following snippet we will only record `SlowJob` if it is over 5 seconds and `VerySlowJob` if it is over 30 seconds.

I know it isn't "per queue" and is "per job", but hopefully it should get you most of the way there.

```php
use Laravel\Pulse\Entry;
use Laravel\Pulse\Facades\Pulse;
use Laravel\Pulse\Value;

Pulse::filter(function (Entry|Value $entry) {
    if ($entry->type !== 'slow_jobs') {
        return true;
    }

    return match ($entry->key) {
        SlowJob::class => $entry->value > 5_000,
        VerySlowJob::class => $entry->value > 30_000,
        default => true,
    };
});
```
