### ISSUE TITLE
Queues not showing in deployed application

### ISSUE THREAD

**Issue by FredrikPAC** [laravel/pulse#308]
### Pulse Version

1.0.0-beta8

### Laravel Version

10.39.0

### PHP Version

8.2

### Livewire Version

3.3.5

### Database Driver & Version

Redis, PSQL

### Description

Hi!
I'm deploying using forge on AWS. I have all the supervisors set up for pulse and queues are running. But i'm not getting any queues showing in Pulse. The odd thing is that everything is working beutifully in the local env.
Any thought or suggestions on how to debug this?
![Screenshot from 2024-02-06 12-48-08](https://github.com/laravel/pulse/assets/98091128/9324f8fe-a613-4d37-9a25-f72eb05fca5c)

### Steps To Reproduce

Just deploying a Laravel 10 app with pulse in forge on AWS is all i've done.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
@FredrikPAC, it is strange that you are not seeing jobs being dispatched.

As a first place to look I would make sure you are logging any exceptions Pulse captures and see if that gives you any insights. It is possible something is going wrong when dispatching jobs and Pulse is silently discarding the exception to ensure your app continues to run as expected.

https://laravel.com/docs/10.x/pulse#pulse-exceptions
