### ISSUE TITLE
Getting Syntax error exception

### ISSUE THREAD

**Issue by kstmostofa** [laravel/pulse#309]
### Pulse Version

1.0@beta

### Laravel Version

10.39.0

### PHP Version

8.2.15

### Livewire Version

3.0.2

### Database Driver & Version

PGSQL 15

### Description

when I am using MySQL as my database driver then pulse is working as expected. but in pgsql driver its throwing Syntax error exception.

![image](https://github.com/laravel/pulse/assets/48328034/557eab1c-36e5-4712-9fab-3d3e538fafb6)

### Steps To Reproduce

when I am using MySQL as my database driver then pulse is working as expected. but in pgsql driver its throwing Syntax error exception.

![image](https://github.com/laravel/pulse/assets/48328034/557eab1c-36e5-4712-9fab-3d3e538fafb6)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
@kstmostofa can you provide the actual exception error? You should be able to see these by clicking "2 vendor frames". Hopefully that should show us where the syntax error is happening.
