### ISSUE TITLE
[Feature Request] Remote Server Recorder

### ISSUE THREAD

**Issue by tobiasvielmetter** [laravel/pulse#319]
Might be interesting to add a remote server recorder to the core functionality.
I have a working prototype in this gist. Might need some work to run under different architectures (currently can run the commands under linux and mac and requires the remote server to be linux). SSH key authentication needs to be in place in order for the commands to be executed.

https://gist.github.com/tobiasvielmetter/44556c542a6b1cbf783ff9e3834c1200

**Comment by jessarcher** [comment]
Interesting idea. We'd wanted to do something similar, but our thought was to create a shell script (or something similar that would be easy to run on a server without PHP) that would run directly on the server being monitored. Your approach is probably easier to set up, but I'm not sure how I feel about continually shelling into a remote server every 15 seconds.

Have you considered creating a package?

**Comment by tobiasvielmetter** [comment]
Ah yes, the shell script approach is a good idea to reduce the amount of ssh requests and to deal with different architectures better. This was just the easiest way to get this working based on the existing server recorder and it does work fine for my current setup. Piping a shell script into the ssh command might also do the trick, so no script installation on the remote server is required (`cat server-stats.sh | ssh 1.2.3.4`). 

Yes, unless you are working on a much better approach, I'd create a package for this. I guess my idea was to drop it here first to see what the response is.

**Comment by tobiasvielmetter** [comment]
I have created a package with the current code https://github.com/wrklst/pulse-remote-server.git
I will work on the package as time permits to improve the performance / reduce the ssh commands etc.
Feel free to close this if you don't see the need to further discuss here. Thanks so much for your input and this Laravel Pulse!

**Comment by driesvints** [comment]
Thanks @tobiasvielmetter!
