### ISSUE TITLE
Too few arguments to function md_to_html

### ISSUE THREAD

**Issue by digitlimit** [laravel/pulse#320]
### Pulse Version

1.0.0-beta.12

### Laravel Version

10.44.0

### PHP Version

8.3.2

### Livewire Version

3.0.2

### Database Driver & Version

Docker

### Description

I am getting this error when I visit /pulse the URL

Too few arguments to function md_to_html(), 0 passed in /var/www/html/storage/framework/views/b7c3271e59f21944eb2fed38185f2383.php on line 11 and exactly 1 expected

![image](https://github.com/laravel/pulse/assets/2041419/4394ae4d-3c57-4c48-8f09-0eb6a4f67447)

### Steps To Reproduce

```
"minimum-stability": "beta",
"prefer-stable": true
```

```
composer require laravel/pulse
```

```
php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
```

```
PULSE_DB_CONNECTION=pulse
```

```
php artisan migrate
```

Visit:  /pulse

**Comment by timacdonald** [comment]
Hi there,

We do not use the `md_to_html` function and as far as I can see none of our dependencies do either.

I have the feeling this might be an issue with a 3rd party card. I would recommend searching your project for `md_to_html` and finding where that function is used. If it does show up in a Pulse file let us know and we can dig into this deeper.
