### ISSUE TITLE
Feat request: log count of all DB queries

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#323]
Hi, I'd like to know how well my cache is working on my platform, it's great knowing the cache hit percentage, but witohut knowing the number of actual count of DB queries I don't know where to add new cache implementations. Can we get a new recorder for counting the number of db queries performed maybe?

**Comment by timacdonald** [comment]
Hi, Ryan, I'm gonna close this one as it is a feature request and not an issue.

I'll make sure the team sees the feature request, but it should be easy to create a third party recorder for this.

**Comment by sts-ryan-holton** [comment]
@timacdonald No worries. Not sure if you're aware, but the "Feature request" button always points to Github issues for this project, thus whyI prefix my question as "feat" :)

![Screenshot 2024-03-04 at 11 34 01](https://github.com/laravel/pulse/assets/25177538/f6e4d953-c250-4efe-affe-0f1832cb9f84)
