### ISSUE TITLE
internal hooks

### ISSUE THREAD

**Issue by ariaieboy** [laravel/pulse#338]
Hi 
Can we hook into the recording lifecycle?
For example, I want to send a notification when a recorder, is stored in the database. 
But I didn't find any way to hook into the lifecycle of the pulse.

**Comment by timacdonald** [comment]
Pulse doesn't currently offer a way to hook into the storage phase.

Pulse stores data in your database, so it would be possible to monitor the `pulse_*` tables and send notifications depending on the data in those table. It would also be possible to create a decorator for the `DatabaseStorage` and send notifications in the `store` method.
