### ISSUE TITLE
Feature request: ability to configure how many days of data is kept in pulse entries

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#345]
Hi,

I'd like the option to configure the maximum number of days that Pulse should retain for my analysis. Right now I see it truncates beyond 7 days. I'd like to be able to limit it to maybe 2 days.

**Comment by driesvints** [comment]
Currently we have this for trimming data: https://laravel.com/docs/11.x/pulse#trimming. Right now we're not actively planning on adding different ways.

**Comment by sts-ryan-holton** [comment]
@driesvints It's been a few hours since I'd set `trim.keep` to "2 days" as opposed to "7 days". Still seeing over 1.4 million entries from 7 days ago. Any ideas?

**Comment by timacdonald** [comment]
Hey there,

The `ingest.trim.keep` is only meant to trim pending entires on the ingest queue, such as those waiting in Redis before being moved to their final destination in storage.

We do not currently allow you to retain less than 7 days of data in Pulse once it has gotten to storage.

**Comment by sts-ryan-holton** [comment]
Ah right. It would be great if such feature could be added. For example. The 1H, 6H, 24H, 7D. Allow to customise the 7D to be maybe 2D, or 14D etc
