### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such column: true

### ISSUE THREAD

**Issue by brunoinds** [laravel/pulse#347]
### Pulse Version

1.0.0-beta14

### Laravel Version

10.48.4

### PHP Version

8.2.17

### Livewire Version

3.0.2

### Database Driver & Version

SQLite on CentOS

### Description

When running the fresh install of  Laravel Pulse on local (MacOS Sonoma M1, MacBook Air), everything works ok. But on server, with CentOS, it throws the following error on oppening the route /pulse:

<img width="1426" alt="image" src="https://github.com/laravel/pulse/assets/49789611/087da44a-d6f9-4cfb-9240-19d80aa31f15">

SQLSTATE[HY000]: General error: 1 no such column: true
`select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then true else null end) as "cache_hit", count(case when ("type" = cache_miss) then true else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated"`

### Steps To Reproduce

php artisan serve

Open the url: localhost:8000/pulse

**Comment by timacdonald** [comment]
@brunoinds, could you please let us know what version of SQLite you are running on the server?

**Comment by timacdonald** [comment]
Could you also try running the following two commands directly against the database and let us know if any of them succeed or fail?

Original...

```sql
select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then true else null end) as "cache_hit", count(case when ("type" = cache_miss) then true else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated"
```

Modified...

```sql
select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then 1 else null end) as "cache_hit", count(case when ("type" = cache_miss) then 1 else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated"
```

**Comment by brunoinds** [comment]
> @brunoinds, could you please let us know what version of SQLite you are running on the server?

SQLite version: 3.7.17

**Comment by brunoinds** [comment]
> Could you also try running the following two commands directly against the database and let us know if any of them succeed or fail?
> 
> Original...
> 
> ```sql
> select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then true else null end) as "cache_hit", count(case when ("type" = cache_miss) then true else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated"
> ```
> 
> Modified...
> 
> ```sql
> select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then 1 else null end) as "cache_hit", count(case when ("type" = cache_miss) then 1 else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated"
> ```

It returns:

`SQLSTATE[HY000]: General error: 1 no such column: cache_hit (Connection: sqlite, SQL: select (select "key" from "pulse_entries" as "keys" where "keys"."key_hash" = "aggregated"."key_hash" limit 1) as "key", "cache_hit", "cache_miss" from (select "key_hash", sum("cache_hit") as "cache_hit", sum("cache_miss") as "cache_miss" from (select * from (select "key_hash", count(case when ("type" = cache_hit) then 1 else null end) as "cache_hit", count(case when ("type" = cache_miss) then 1 else null end) as "cache_miss" from "pulse_entries" where "type" in (cache_hit, cache_miss) and "timestamp" >= 1711483641 and "timestamp" <= 1711483679 group by "key_hash") union all select * from (select "key_hash", sum(case when ("type" = cache_hit) then "value" else null end) as "cache_hit", sum(case when ("type" = cache_miss) then "value" else null end) as "cache_miss" from "pulse_aggregates" where "period" = 60 and "type" in (cache_hit, cache_miss) and "aggregate" = count and "bucket" >= 1711483680 group by "key_hash")) as "results" group by "key_hash" order by "cache_hit" desc limit 101) as "aggregated")`

**Comment by crynobone** [comment]
> SQLite version: 3.7.17

Do note that Laravel 10 requires `3.8.8` and Laravel 11 requires `3.35.0` as minimum.

https://laravel.com/docs/10.x/database

**Comment by brunoinds** [comment]
> > SQLite version: 3.7.17
> 
> Do note that Laravel 10 requires `3.8.8` and Laravel 11 requires `3.35.0` as minimum.
> 
> https://laravel.com/docs/10.x/database

Ok! I did not realized that. Thanks!
