### ISSUE TITLE
Feature Request: Extend nav bar with items

### ISSUE THREAD

**Issue by buddhaCode** [laravel/pulse#348]
Hi,
I would like to extend the nav bar with additional items. Between the Logo and the period selector is lots of space for it. I need this to place a button back to the admin panel.

I didn't see any chance to override or customize the `pulse` blade file. Sure, I could use another layout in my `dashboard` blade. But then I had to copy the whole content from the `pulse` blade file. Think thats bit verbose.

A named slot in the `pulse` blade would be nice.

Would you accept a PR for that?

Best, Arne

**Comment by driesvints** [comment]
Heya. If you can attempt a PR so we can look at some code we can maybe consider it. Thanks!

**Comment by buddhaCode** [comment]
Sure. I placed a PR to get a better understanding.
