### ISSUE TITLE
Dashboard with empty screen

### ISSUE THREAD

**Issue by yurih567** [laravel/pulse#352]
### Pulse Version

v1.0.0-beta16

### Laravel Version

v11.2.0

### PHP Version

8.2.17

### Livewire Version

v3.4.10

### Database Driver & Version

MySQL 8.0.32

### Description

After installing the lib, when trying to access the dashboard, only an empty page is returned

![image](https://github.com/laravel/pulse/assets/45864246/caefce4f-c1a0-4ed0-914a-17b21def33ea)

### Steps To Reproduce

Run the following commands:

composer require laravel/pulse
php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
php artisan migrate

**Comment by jbrooksuk** [comment]
Does your application have any custom configurations for Blade? It looks like only the raw Blade is being returned rather than the compiled HTML.

**Comment by yurih567** [comment]
> Does your application have any custom configurations for Blade? It looks like only the raw Blade is being returned rather than the compiled HTML.

I'm using `Blade::withoutComponentTags();`, removing this and clearing the view cache worked.
thanks
