### ISSUE TITLE
Laravel pulse returns 404

### ISSUE THREAD

**Issue by hariprashadganeshan** [laravel/pulse#381]
### Pulse Version

1.0

### Laravel Version

10.0

### PHP Version

8.2

### Livewire Version

3.5

### Description

Integrated pulse successfully. When tried to access its not working. On inspection it shows livewire/update not found.
![Screenshot from 2024-05-27 12-29-13](https://github.com/laravel/pulse/assets/35491138/f59a2b4d-5186-4ba6-8100-90828ef20951)

### Steps To Reproduce

Install pulse 
access the dashboard

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
