### ISSUE TITLE
Could not publish migrations as per instructions

### ISSUE THREAD

**Issue by avioli** [laravel/pulse#396]
### Pulse Version

1.2.4

### Laravel Version

11.16.0

### PHP Version

8.2.20

### Livewire Version

3.5.4

### Description

Following the [installation guide](https://laravel.com/docs/11.x/pulse#installation), which advises to run vendor:publish to publish the Pulse config and migrations did not work for me:

```
$ php artisan vendor:publish --provider='Laravel\Pulse\PulseServiceProvider'

   INFO  No publishable resources for tag [].  
```

Only publishing with a `--tag` did put the relevant migration in place:

```
$ php artisan vendor:publish --tag="pulse-migrations"

   INFO  Publishing [pulse-migrations] assets.  

  Copying directory [vendor/laravel/pulse/database/migrations] to [database/migrations] ....................................................... DONE
```

### Steps To Reproduce

See description above.

**Comment by timacdonald** [comment]
Hi, @avioli, thanks for reporting this.

I just ran the installation against a clean install and all seems to be working.

I wonder if this has something to do with you using single quotes or if there is something weird going on with the escape characters.

What terminal / shell are you using?

<img width="1393" alt="Screenshot 2024-07-22 at 09 25 40" src="https://github.com/user-attachments/assets/6c5c386d-59bd-4fc0-acd3-f5ddf0be6568">

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
