### ISSUE TITLE
Error: Control character error, possibly incorrectly encoded

### ISSUE THREAD

**Issue by rebbieboi** [laravel/pulse#401]
### Pulse Version

v1.2.4

### Laravel Version

11.20.0

### PHP Version

8.2.22

### Livewire Version

v3.5.4

### Description

this just started happening out of nowhere but Laravel pulse will return an error "Control character error, possibly incorrectly encoded" via "app / Http / Middleware / GeneralChecks.php". Also, it will load briefly and show some components before the error appears so I'm guessing the problem is with "Laravel\Pulse\Livewire\SlowQueries" since it's the one showing in the error logs.

also, for some reason pulse was doing a lot of insert queries in the DB and it caused our DB to freeze so I had to restart the DB and after that, this error started appearing.

it works fine on php8.1 using Laravel 10.x

### Steps To Reproduce

have a laravel pulse running in php8.2 and laravel 11.x

**Comment by timacdonald** [comment]
@rebbieboi, it sounds like there might be corrupt data in the Pulse tables.

I also _highly_ recommend you don't use the `storage` ingest in production and instead use the [`redis` ingest](https://laravel.com/docs/11.x/pulse#ingest). The Redis ingest will scale and protect your database when you have high volume traffic.

You may need to truncate the pulse tables, or just those impacted (queries?), to remove the corrupt data.

**Comment by rebbieboi** [comment]
> @rebbieboi, it sounds like there might be corrupt data in the Pulse tables.
> 
> I also _highly_ recommend you don't use the `storage` ingest in production and instead use the [`redis` ingest](https://laravel.com/docs/11.x/pulse#ingest). The Redis ingest will scale and protect your database when you have high volume traffic.
> 
> You may need to truncate the pulse tables, or just those impacted (queries?), to remove the corrupt data.

thank you! will give that a try. Don't worry we only use this in our dev box.

**Comment by timacdonald** [comment]
Good to hear. Hopefully that gets you back on track.
