### ISSUE TITLE
I followed the documentation. Despite installing and setting up everything, I always get a 404 error when I try to hit the /pluse route.

### ISSUE THREAD

**Issue by ch-kashif171** [laravel/pulse#402]
### Pulse Version

1.2

### Laravel Version

11.20.0

### PHP Version

8.3.2

### Livewire Version

3.0.2

### Database Driver & Version

mysql 8.0.30

### Description

I followed the official documentation. Despite installing and setting up everything, I always get a 404 error when I try to hit the /pluse route.

I don't know what I might be missing. Please guide me.

### Steps To Reproduce

I followed the documentation and after installing pulse and setting up db and other things, when I tried to hit pulse route it always give me **404 error** and it seems something is missing on code level.

![screenshot](https://github.com/user-attachments/assets/eb096c13-5ecf-46c2-8c1c-0e9076e11c01)

**Comment by jessarcher** [comment]
Hey @Kashif-Kframe,

It looks like you've got a typo in the path - it should be `/pulse` rather than `/pluse`.
