### ISSUE TITLE
not work without php artisan serve

### ISSUE THREAD

**Issue by omidmousavi** [laravel/pulse#405]
### Pulse Version

v1.2.5

### Laravel Version

11.22.0

### PHP Version

8.3.6

### Livewire Version

3.5.6

### Database Driver & Version

MySql

### Description

When i use `php artisan serve` everything is okay.
but in production i use apache and project run without artisan command
and this make some error at livewire/update route :(
![image](https://github.com/user-attachments/assets/e3745b2c-bd6c-4e4c-b17b-e656a15a17c3)

### Steps To Reproduce

I just setup everything like laravel docs
https://laravel.com/docs/11.x/pulse

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by shealavington** [comment]
Looks like your path has a funny offset, your path probably shouldn't include /public as it looks like you'll have directory traversal issues.

You should fix that so your path is `website.com/pulse` only, and then it should start working.

**Comment by omidmousavi** [comment]
Thank you..
It means i have to wait for you to fix this?

**Comment by shealavington** [comment]
No. This is a problem with _your_ setup. Not the package.
