### ISSUE TITLE
Pulse showing CPU: 100% all the time.

### ISSUE THREAD

**Issue by NegusNati** [laravel/pulse#408]
### Pulse Version

1.2

### Laravel Version

11.9

### PHP Version

8.2

### Livewire Version

3.4.9

### Database Driver & Version

mariadb:11.0

### Description

![image](https://github.com/user-attachments/assets/70ca6215-c0ce-4b2a-997f-0cb358e3cea4)

I am using pulse for my open source project and i get CPU 100% all the time while the other stats are working fine. 

### Steps To Reproduce

fork https://github.com/NegusNati/passport.et and configure the .env file for it. 

use the docker-compose.prod.yml file to build the images.

**Comment by jbrooksuk** [comment]
Can you verify what the true CPU usage is on the server by running `htop` or `top`?

**Comment by NegusNati** [comment]
![image](https://github.com/user-attachments/assets/7e526b6e-4a24-410b-a73f-4e5e043be15d)
sorry it was a malware (the famous kdevtmpfsi apparently) from php-fpm docker image or maybe a misconfiguration of my containers [src](https://stackoverflow.com/questions/60151640/kdevtmpfsi-using-the-entire-cpu), now it is working normally as you would expect. but thanks tho, i wouldn't have found out this early if it wasn't for this tool. the service been live for two weeks i didn't check.
![image](https://github.com/user-attachments/assets/26eefe55-5c8a-4600-a802-ff86c7483e64)

**Comment by NegusNati** [comment]
thanks

**Comment by jessarcher** [comment]
Thanks for the update @NegusNati! Glad you caught the malware!
