### ISSUE TITLE
[Bug] `Application Usage` increases based on Pulse requests

### ISSUE THREAD

**Issue by devajmeireles** [laravel/pulse#409]
### Pulse Version

v1.2.5

### Laravel Version

11.25.0

### PHP Version

PHP 8.3.12 (cli) (built: Sep 27 2024 00:18:43) (NTS)

### Livewire Version

v3.5.8

### Database Driver & Version

SQLite

### Description

I'll be honest in saying that I don't know if this is a bug, but at least it seems confusing. 

I've had Pulse in production for 4 days, and I noticed a significant increase in the numbers for `Application Usage` -> `Top 10 users: making requests`. Only today I discovered the reason: we're using Pulse in production and performing browser refreshes to follow some data in real-time. 

The first Pulse card is `Application Usage`, where the term "Application", IMHO, means that it refers to the application, but the **requests made to Pulse are counted as requests of the application.** Today we've 32 people in the project and daily we've approximately 15 devs (the entire dev team) viewing Pulse all the time.

If this IS NOT A BUG, ​​wouldn't it be correct to rename this board? When we say "application", we might think that it is just really the application, and Pulse is not exactly the application, or part of it.

Demo _(locally)_:
![CleanShot 2024-09-27 at 23 23 28](https://github.com/user-attachments/assets/2d53c090-e4e6-4910-a4c0-f3f7ecf7e096)

### Steps To Reproduce

1. Install Pulse
2. Access the Pulse dashboard
3. Refresh the browser a lot of times, you'll be able to see what I'm saying

**Comment by ArcoVoets** [comment]
There is an [option in the config file](https://github.com/laravel/pulse/blob/5dd3cd257305c796900a69d3307fea3de1425813/config/pulse.php#L227) to ignore certain route patterns. This is set to ignore the pulse route by default. Can you check whether the pulse route is still listed in the ignored routes?

The [docs](https://laravel.com/docs/11.x/pulse#user-requests-recorder) also mention this.

**Comment by timacdonald** [comment]
I'm unable to replicate this on a fresh application installation.

We will need some more information on how to replicate the issue, a replication repository, or to see your `config/pulse.php` configuration file.

The only way I could replicate this behaviour is by commenting out the ignore configuration in `config/pulse.php`.

```diff
        Recorders\UserRequests::class => [
            'enabled' => env('PULSE_USER_REQUESTS_ENABLED', true),
            'sample_rate' => env('PULSE_USER_REQUESTS_SAMPLE_RATE', 1),
            'ignore' => [
-               '#^/'.env('PULSE_PATH', 'pulse').'$#', // Pulse dashboard...
                '#^/telescope#', // Telescope dashboard...
            ],
        ],
```

You could use Pulse to debug this. If you set the slow outgoing requests threshold to zero and make sure the ignores for `Recorders\SlowRequests` match `Recorders\UserRequests`. The requests it is counting should then show up as slow requests.

**Comment by devajmeireles** [comment]
> I'm unable to replicate this on a fresh application installation.
> 
> We will need some more information on how to replicate the issue, a replication repository, or to see your `config/pulse.php` configuration file.
> 
> The only way I could replicate this behaviour is by commenting out the ignore configuration in `config/pulse.php`.
> 
> ```diff
>         Recorders\UserRequests::class => [
>             'enabled' => env('PULSE_USER_REQUESTS_ENABLED', true),
>             'sample_rate' => env('PULSE_USER_REQUESTS_SAMPLE_RATE', 1),
>             'ignore' => [
> -               '#^/'.env('PULSE_PATH', 'pulse').'$#', // Pulse dashboard...
>                 '#^/telescope#', // Telescope dashboard...
>             ],
>         ],
> ```
> 
> You could use Pulse to debug this. If you set the slow outgoing requests threshold to zero and make sure the ignores for `Recorders\SlowRequests` match `Recorders\UserRequests`. The requests it is counting should then show up as slow requests.

I'll close this for now. If it happens again I'll get all the necessary data. I couldn't reproduce it anymore, but I'm sure I didn't mess with the config file.

**Comment by timacdonald** [comment]
No worries. Yell out if you see it again.
