### ISSUE TITLE
Error getting spammed in my Logfile (only when Pulse + debugbar combined) => only when calling /pulse resources

### ISSUE THREAD

**Issue by avn-dev** [laravel/pulse#412]
### Pulse Version

1.2.5

### Laravel Version

11.28.1

### PHP Version

8.3.12

### Livewire Version

3.5.12

### Database Driver & Version

sqlite

### Description

In combination with barryvdh/laravel-debugbar (3.14.3) I'm getting this error spammed in my logfile when visiting / viewing a pulse resource (/pulse)

[2024-10-17 03:39:08] local.ERROR: Debugbar exception: Strings with null bytes cannot be escaped. Use the binary escape option.  

### Steps To Reproduce

installing laravel, debugbar, pulse
=> calling /pulse

**Comment by crynobone** [comment]
It's probably best to disable `pulse` route from Debugbar configuration

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
Looks like this is a bug in the debugbar, where it is unable to correctly handled collections being cached.

This reproduces the issue on a fresh laravel installation without Pulse.

```php
// routes/web.php

Route::get('/', function () {
    $collection = collect([1, 2, 3]);

    \Cache::put('collection', $collection);

    return view('welcome');
});
```
