### ISSUE TITLE
Servers watcher is not visible on Octane (Swoole)

### ISSUE THREAD

**Issue by hasancanboga** [laravel/pulse#420]
### Pulse Version

v1.2.6

### Laravel Version

v11.30.0

### PHP Version

8.3.13

### Livewire Version

v3.5.12

### Database Driver & Version

mysql  Ver 8.0.40-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Description

On Laravel Octane (v2.5.9) running with Swoole (php-swoole v5.1.4), the Servers card on top of the default pulse page, which shows  the CPU and RAM usage, is not showing up. 

### Steps To Reproduce

Install php-swoole extension, laravel octane, and set `OCTANE_SERVER=swoole` in .env file. 
Run laravel using `php artisan octane:start`.
Then go to http://127.0.0.1:8000/pulse

The same issue happens for an actual production server running octane through nginx.

**Comment by jessarcher** [comment]
Hi @hasancanboga,

I can't think of any reason why Octane would have an impact on the servers card. The main reason that servers would not appear is when there is no server data in the Pulse database tables.

Can you please confirm that the `pulse:check` command is running?

https://laravel.com/docs/11.x/pulse#capturing-entries

**Comment by hasancanboga** [comment]
> Hi @hasancanboga,
> 
> I can't think of any reason why Octane would have an impact on the servers card. The main reason that servers would not appear is when there is no server data in the Pulse database tables.
> 
> Can you please confirm that the `pulse:check` command is running?
> 
> https://laravel.com/docs/11.x/pulse#capturing-entries

Oh sorry I didn't realize I was supposed to have a supervisor process running for the `pulse:check` command in order to make servers watcher work. Did not check that part on docs, my bad. Thanks for the info, it works now! @jessarcher
