### ISSUE TITLE
Messed up timezones after PR #417

### ISSUE THREAD

**Issue by maciek-szn** [laravel/pulse#422]
### Pulse Version

1.2.6

### Laravel Version

11.33.2

### PHP Version

8.3.13

### Livewire Version

3.5.12

### Description

After #417 timezones are messed up much more than before.

It's 16:56 CET here now.

CPU and memory graphs show UTC time (so 1 hour back):
![obraz](https://github.com/user-attachments/assets/cedc0382-cecb-4ef9-a262-93221b4df908)

Queues graph shows CET time (correct):
![obraz](https://github.com/user-attachments/assets/288b64cf-389f-4c7f-bf26-20e1737b9fe4)

However queues card title tooltip shows some mystery timezone (1 hour forward, definitely not CET):
![obraz](https://github.com/user-attachments/assets/8e3a1af2-e89a-40e6-bb5b-4bd2b6eaf851)

Custom cards just use UTC. I'm guessing they should be manually modified by their authors, but do the authors know about it?

### Steps To Reproduce

Just observe the Pulse cards.

**Comment by timacdonald** [comment]
Thanks for raising this one. Looks like the graph update mechanism was missed on this one for the memory and CPU stats, as they slightly vary from the queue implementation.

I've opened a PR to address the wrong formatting after updates: https://github.com/laravel/pulse/pull/423

If custom cards want to format their dates, they will need to manually make this happen. There is a global `window.formatDate` function available if they wish to use it. But they can also implement their own formatting if they wish.

I'm unable to replicate the issue with the queues card date. If you can provide the steps to reproduce the problem I will reopen the issue and dive into it.

**Comment by maciek-szn** [comment]
> I'm unable to replicate the issue with the queues card date. If you can provide the steps to reproduce the problem I will reopen the issue and dive into it.

There are no specific steps to reproduce. It just works that way. I can describe the server and client configuration.

Server:
- OS: Ubuntu 24.04
- OS timezone: Europe/Warsaw
- Laravel app timezone: Europe/Warsaw
- php.ini timezone: Europe/Warsaw

Client:
- OS: Windows (tested on 10 & 11)
- OS timezone: Europe/Warsaw
- browser: Firefox 132.0.2, Chrome 131.0.6778.86

The tooltip issue occurs not only on the Queues card, but on other cards as well.

**Comment by timacdonald** [comment]
Hmm. Can you please try upgrading to `v1.2.7`, which we released yesterday, and then running `php artisan view:clear` and let me know which issues are remaining?

**Comment by maciek-szn** [comment]
Sure. Unfortunately nothing has changed. It's 20:13 CET here and the tooltip shows 21:13 CET.

![obraz](https://github.com/user-attachments/assets/a0a1cbac-c4e8-477f-8bb6-f58cf03ae1c0)

The CPU and Memory graphs work fine in 1.2.7.

**Comment by timacdonald** [comment]
Appreciate you checking this again.

I've opened a PR to fix this: https://github.com/laravel/pulse/pull/425
