### ISSUE TITLE
Custom viewPulse Gate not working

### ISSUE THREAD

**Issue by MarcelWeidum** [laravel/pulse#75]
### Pulse Version

1.0.0-beta1

### Laravel Version

10.34.2

### PHP Version

8.2.12

### Description

When I define the following Gate in the `boot` method of  `app\Providers\AuthServiceProvider.php`
```php
Gate::define('viewPulse', function (User $user) {
    return true;
});
```

I still get a 403 error. This is ofcourse happening in production.

### Steps To Reproduce

1.
Set up a new laravel app (using sail).

2.
Change the composer minimum stability

3.
`composer require laravel/pulse`

4.
Migrate db

5.
Change .env to production

6.
Clear cache

7.
Define Gate as described in my issue above

8.
Browse to `/pulse`

**Comment by tominal** [comment]
Did you remember to authenticate as a user? I did the same thing.

**Comment by MarcelWeidum** [comment]
> Did you remember to authenticate as a user? I did the same thing.

I did not know that `Gate` requires to be authenticated. I thought if I returned `true` the Gate will accept it.

Thanks!

**Comment by timacdonald** [comment]
The default Gate that ships with Pulse allows access to non-logged-in users when the `APP_ENV` is set to `"local"`.

Make sure you have updated to the latest version of Pulse.

@MarcelWeidum a gate supports unauthenticated users if the `$user` object is nullable.

```diff
- Gate::define('viewPulse', function (User $user) {
+ Gate::define('viewPulse', function (?User $user = null) {
    return true;
});
```
