### ISSUE TITLE
Name attribute on User model

### ISSUE THREAD

**Issue by joostvanhoof** [laravel/pulse#82]
Thanks for this amazing package!

When trying the beta I noticed that the `name` attribute that I have set on the user model doesn't work:

```php
public function getNameAttribute()
{
  return $this->first_name.' '.$this->last_name;
}
```

I read that it's possible to customize the user resolution and display by invoking the `Pulse::users` method in the  `AppServiceProvider`, but it might be nice if it uses the attribute if it's defined, if possible (not sure).

**Comment by pyr0hu** [comment]
@joostvanhoof isn't these kindof attributes deprecated? could you try with the new one with Attribute::make?

```php
protected function name(): Attribute
{
    return Attribute::make(get: fn () => $this->first_name.' '.$this->last_name);
}
```

**Comment by toitzi** [comment]
@joostvanhoof Do you have any special configuration / model? Because i tried what you did and it workes flawlessly, having a quick look at the pulse source it should also work for you

**Comment by toitzi** [comment]
Oh i get it, you are not overwriting a column with your attribute function, but rather creating a new one, understood, thats why it worked for me and not for you.

Yes the problem probably happens [here](https://github.com/laravel/pulse/blob/1de2604de554c6a0c8c29f706615b4e30995628d/src/Pulse.php#L328C16-L328C16) in the resolveUsers function as there the columns is read:

```
public function resolveUsers(Collection $ids): Collection
{
    if ($this->usersResolver) {
        return collect(($this->usersResolver)($ids));
    } elseif (class_exists(\App\Models\User::class)) {
        return \App\Models\User::whereKey($ids)->get(['id', 'name', 'email']);
    } elseif (class_exists(\App\User::class)) {
        return \App\User::whereKey($ids)->get(['id', 'name', 'email']);
    }

    return $ids->map(fn (string|int $id) => [
        'id' => $id,
        'name' => "User ID: {$id}",
    ]);
}
```

You probaly need to overwrite the user resolver as you do above..i thnik that is the recommended solution in this case
