### ISSUE TITLE
Migration are mysql specific, fails on other databases

### ISSUE THREAD

**Issue by nurdism** [laravel/pulse#83]
### Pulse Version

1.0.0 beta

### Laravel Version

10.34.2

### PHP Version

8.3.0

### Description

Migration throws sql error when using postgresql 15

### Steps To Reproduce

run `php artisan migrate` 

```
   INFO  Running migrations.  

  2023_06_07_000001_create_pulse_tables ................................................................................................... 4ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")"
LINE 1: ...(16) not null generated always as (unhex(md5(`key`))), "valu...
                                                             ^ (Connection: pgsql, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar(255) not null, "key" text not null, "key_hash" char(16) not null generated always as (unhex(md5(`key`))), "value" text not null))
 ```

**Comment by Kuzuto** [comment]
Have same problem with sqlite on my tests.
md5 is not supported on sqlite

Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such function: md5 (Connection: sqlite, SQL: create table "pulse_values" ("timestamp" integer not null, "type" varchar not null, "key" text not null, "key_hash" varchar as (unhex(md5(`key`))), "value" text not null))
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:574
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:788
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:755
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
at vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:110
at vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:439
at vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:281
at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:353
at vendor/laravel/pulse/database/migrations/2023_06_07_000001_create_pulse_tables.php:23
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:493
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:410
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:419
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:216
at vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php:37
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:756
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:216
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:181
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:124
at vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:90
at vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:633
at vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:83
at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
at vendor/laravel/framework/src/Illuminate/Container/Util.php:41
at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
at vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
at vendor/laravel/framework/src/Illuminate/Container/Container.php:662
at vendor/laravel/framework/src/Illuminate/Console/Command.php:211
at vendor/symfony/console/Command/Command.php:326
at vendor/laravel/framework/src/Illuminate/Console/Command.php:180
at vendor/symfony/console/Application.php:1063
at vendor/symfony/console/Application.php:320
at vendor/symfony/console/Application.php:174
at vendor/laravel/framework/src/Illuminate/Console/Application.php:162
at vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:400
at vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:296
at vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:481
at vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:80
at vendor/laravel/framework/src/Illuminate/Foundation/Testing/RefreshDatabase.php:47
at vendor/laravel/framework/src/Illuminate/Foundation/Testing/RefreshDatabase.php:22
at vendor/laravel/framework/src/Illuminate/Foundation/Testing/LazilyRefreshDatabase.php:27
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:744
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:533
at vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32
at vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3387
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1968
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1333
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1298
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1137
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:338
at vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:236
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:333
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:287
at database/factories/UserFactory.php:22
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:454
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:433
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:417
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:155
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:416
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:390
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:284

**Comment by nurdism** [comment]
```php
$table->char('key_hash', 16)->charset('binary')->virtualAs('unhex(md5(`key`))');
```

is the issue, that is mysql specific

**Comment by jbrooksuk** [comment]
This is a documented limitation of Pulse.
