### ISSUE TITLE
livewire.js gives 404 in production

### ISSUE THREAD

**Issue by joostvanhoof** [laravel/pulse#85]
### Pulse Version

v1.0.0-beta2

### Laravel Version

10.34.2

### PHP Version

8.2.10

### Description

In production, the asset `/livewire/livewire.js?id=eaa5c323` in the Network tab shows up as 404 Not Found. If I paste the full  URL (including the domain name) to the asset in the browser, it does load. This does not happen locally.

Because of this, the dashboard only shows the skeleton loading state.

### Steps To Reproduce

Deploy to production I guess 😅

**Comment by adriweb** [comment]
Hitting this issue as well.
It would seem that `Laravel\Pulse\Facades\Pulse::js()` returns a path from the root of the domain instead of taking into account the env's `APP_URL`... maybe?

**Comment by adriweb** [comment]
Alright, this is mentioned in the docs: https://livewire.laravel.com/docs/installation#customizing-the-asset-url

That said, the default behaviour, once you `composer require` it, may lead people to think it's broken, which is unfortunate.

**Comment by binumathew** [comment]
Pulse Version
v1.0.0-beta2

Laravel Version
10.34.2

PHP Version
8.2.10

In my case http://localhost:8000/pulse return 404

**Comment by marianmirzacu** [comment]
I had the same error and I have found the following fix:
- you need to install livewire via composer (composer require livewire/livewire)
- if you are using nginx as a webserver add the following lines to your config

```
location = /livewire/livewire.js {
    expires off;
    try_files $uri $uri/ /index.php?$query_string;
}
```

source: https://benjamincrozat.com/livewire-js-404-not-found

**Comment by timacdonald** [comment]
Seems this isn't an issue with Pulse specifically, but a configuration issue of the consuming application.

Will close this and would welcome suggestions if there are improvements we can make here.

**Comment by timacdonald** [comment]
Opened a PR to address this moving forward: https://github.com/laravel/pulse/pull/266
