### ISSUE TITLE
SQLite Unsupported

### ISSUE THREAD

**Issue by devajmeireles** [laravel/pulse#90]
### Pulse Version

Beta

### Laravel Version

Latest

### PHP Version

8.1

### Description

The documentation doesn't mention this, but when I tried to install locally using `sqlite`, I got an error related to the `md5` function:

![CleanShot 2023-12-01 at 18 44 47](https://github.com/laravel/pulse/assets/60591772/2c0527e3-2c91-4e83-9b56-0f17b7debc1b)

### Steps To Reproduce

Try to install Pulse in any application that uses SQLite as the default database.

**Comment by elmarzouguidev** [comment]
Pulse's first-party storage implementation currently requires a **MySQL** database

**Comment by stevebauman** [comment]
@devajmeireles You will have to call `Pulse::ignoreMigrations()` in your test suite or if your DB connection is `sqlite` 👍 

```php
abstract class TestCase extends BaseTestCase
{
    /**
     * Setup the test environment.
     */
    protected function setUp(): void
    {
        parent::setUp();

        Pulse::ignoreMigrations();
    }
}
```

**Comment by timacdonald** [comment]
You probably want to disable Pulse altogether in your testsuite.

`PULSE_ENABLED=false`

**Comment by SRWieZ** [comment]
Yep! Figured out later and this is way more easier too 🙂
