### ISSUE TITLE
Allow for name variations on users

### ISSUE THREAD

**Issue by n-va** [laravel/pulse#92]
### Pulse Version

v1.0.0-beta2

### Laravel Version

10.33.0

### PHP Version

8.2.12

### Description

Updating the user model to use a first_name and last_name results in an error exception for the missing name field

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'

### Steps To Reproduce

Remove the name field from the User model

**Comment by toitzi** [comment]
Similiar to #82, you can try the same [solution](https://github.com/laravel/pulse/issues/82#issuecomment-1836677468) as there and overwrite the user resolver
