### ISSUE TITLE
Pulse keeps loading livewire component, does not render

### ISSUE THREAD

**Issue by ysrdevs** [laravel/pulse#98]
### Pulse Version

1.0.0

### Laravel Version

10.4.1

### PHP Version

8.3

### Description

<img width="1750" alt="Screenshot 2023-12-01 at 8 59 39 PM" src="https://github.com/laravel/pulse/assets/32823553/54a25684-2013-4055-9263-84a712396ec7">

The database has pulse data and I can see recorded activity there as well but the /pulse route is not displaying the data. Same on local machine using Laravel Herd and also on Laravel Forge online

### Steps To Reproduce

`composer require laravel/pulse
`
`php artisan migrate
`

The /pulse route shows the pulse menu but no data

**Comment by ahinkle** [comment]
What exceptions / console log errors are you getting?

**Comment by ysrdevs** [comment]
> What exceptions / console log errors are you getting?

No error log in console, If I test on Forge I don't see anything in the logs either.

<img width="2056" alt="Screenshot 2023-12-01 at 9 05 36 PM" src="https://github.com/laravel/pulse/assets/32823553/0c311768-8782-4d05-b305-9b0275a2a766">

**Comment by attaryz** [comment]
i also recieved this error.

**Comment by ahinkle** [comment]
Interesting. What's your output on `php artisan about`?

**Comment by attaryz** [comment]
i got it to work by disabling the CORS middleware.

**Comment by PerryvanderMeer** [comment]
@ysrdevs any chance you use Livewire in your project and have `inject_assets` disabled? Looks like Livewire isn't loaded at all.

**Comment by ysrdevs** [comment]
> Interesting. What's your output on `php artisan about`?
> 
> Is this a duplicate of #85?

This is what I get

`php artisan about`

Environment ..........................................................................................................
  Application Name ........................................................................................... Mediscope
  Laravel Version .............................................................................................. 10.34.2
  PHP Version .................................................................................................... 8.3.0
  Composer Version ............................................................................................... 2.5.5
  Environment .................................................................................................... local
  Debug Mode ....................................................................................................... OFF
  URL .................................................................................................... websitename.com
  Maintenance Mode ................................................................................................. OFF

  Cache ................................................................................................................
  Config .................................................................................................... NOT CACHED
  Events .................................................................................................... NOT CACHED
  Routes .................................................................................................... NOT CACHED
  Views ......................................................................................................... CACHED

  Drivers ..............................................................................................................
  Broadcasting ..................................................................................................... log
  Cache ........................................................................................................... file
  Database ....................................................................................................... mysql
  Logs .................................................................................... stack / single, daily, flare
  Mail ............................................................................................................ smtp
  Octane .................................................................................................... roadrunner
  Queue ........................................................................................................... sync
  Session ......................................................................................................... file

  Livewire .............................................................................................................
  Livewire ...................................................................................................... v3.2.2

**Comment by ysrdevs** [comment]
> @ysrdevs any chance you use Livewire in your project and have `inject_assets` disabled? Looks like Livewire isn't loaded at all (see #87 and #88).

This solves it.

Adding @livewireScripts just before the closing </body> tag fixes it. The issue is with livewire not injecting assets to the pulse dashboard.

**Comment by gofish543** [comment]
Similar issue, needed to add...
```blade
    @livewireScriptConfig(['nonce' => Vite::cspNonce()])
    @livewireStyles(['nonce' => Vite::cspNonce()])
```

to the dashboard.blade.php file

I have inject_assets disabled
